Maximum likelihood estimator (MLE) in logistic regression
================
S. Sudhir
2023-08-16

# Optimization for Maximum Likelihood Estimation

## MLE for mean and standard deviation of a random sample from $N(\mu, \sigma)$

Here we’ll use optimization to confirm that, given a simple random
sample $X_1, \ldots, X_n \sim N(\mu, \sigma^2)$, the maximum-likelihood
estimates for the unknown mean $\mu$ and standard deviation $\sigma$ are

$$\mu = \frac{1}{n} \sum_{i=1}^n X_i$$

and

$$\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^n (X_i - \mu)^2}$$

Since each $X_i \sim N(\mu, \sigma^2)$ has the probability density
function

$$f(x_i; \mu, \sigma) = \frac{1}{\sqrt{2 \pi} \sigma} \exp\left(-\frac{(x_i - \mu)^2}{2 \sigma^2}\right)$$

``` r
## Function for Normal Probability Density Function
norm_pdf = function(x, mean, sd)
{
  return(1/(sqrt(2*pi)*sd) * exp((-1/(2*sd^2))*(x - mean)^2))
}
```

and the $X_i$’s are independent, the density function for the sample is

$$f(x_1, \ldots, x_n; \mu; \sigma) = \prod_{i=1}^n f(x_i; \mu, \sigma) = \left(\frac{1}{\sqrt{2 \pi} \sigma}\right)^n \exp\left(-\frac{1}{{2 \sigma^2}} \sum_{i=1}^n (x_i - \mu)^2\right)$$

If we now consider the sample $(x_1, \ldots, x_n)$ as fixed, then
$f(x_1, \ldots, x_n; \mu; \sigma)$ can be regarded as a function of
$\mu$ and $\sigma$ called the likelihood, $L$:

$$L(\mu, \sigma; x_1, \ldots, x_n) = f(x_1, \ldots, x_n; \mu; \sigma)$$

We want to use optimization to find the $(\mu, \sigma)$ pair that
maximizes $L(\mu, \sigma; x_1, \ldots, x_n)$. However, computing $L$ is
problematic because its product of small numbers often leads to
underflow, in which the product is closer to zero than a computer can
represent with the usual floating-point arithmetic. Taking logarithms
addresses this problem by transforming products of very small positive
numbers to sums of moderate negative numbers. For example, $10^{-10}$ is
very small, but $\log(10^{-10}) \approx -23.03$ is moderate. With this
in mind, the log likelihood $l$ is

$$l(\mu, \sigma; x_1, \ldots, x_n) = \log\left(L(\mu, \sigma; x_1, \ldots, x_n)\right) = n \log\left(\frac{1}{\sqrt{2 \pi} \sigma}\right) -\frac{1}{{2 \sigma^2}} \sum_{i=1}^n (x_i - \mu)^2$$

``` r
## Log Likelihood Function where par = c(mean, sd)
Log.Lik = function(par, x)
{
  n = length(x)
  lik1 = n * log(1/(sqrt(2*pi)*par[2]))
  lik2 =  1/(2*par[2]^2) * sum((x - par[1])^2)
  
  return (-(lik1 - lik2)) # Returning negative so as to find maximum
}
```

Since the logarithm is an increasing function, the maximum of $l$ occurs
at the same location $(\mu, \sigma)$ as the maximum of $L$.

### Using `optim()` with its default Nelder-Mead method to find the estimates of $\mu$ and $\sigma$ that maximize $l$ over the data $x_1, \ldots, x_n =$ `mtcars$mpg`

``` r
## Optimizing Log-Likelihood to find parameter estimates
opt.par = optim(par = c(.5, .5), 
             fn = Log.Lik, 
             x = mtcars$mpg,
             method = 'Nelder-Mead',
             upper = Inf,
             lower = -Inf)

opt.par
```

    ## $par
    ## [1] 20.10088  5.94055
    ## 
    ## $value
    ## [1] 102.3779
    ## 
    ## $counts
    ## function gradient 
    ##       89       NA 
    ## 
    ## $convergence
    ## [1] 0
    ## 
    ## $message
    ## NULL

    ## [1] "The par = (mean, sd) estimations for Log-Likelihood using Nelder-mead is (20.100877, 5.940550)"

### Checking estimates by comparing them to the sample mean and (population) standard deviation.

    ## [1] "The mean and sd estimate using mle and Nelder-Mead optimization is (20.100877, 5.940550)"

    ## [1] "The mean and sd of the data mtcars$mpg is (20.090625, 6.026948)"

![](Maximum_Likelihood_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

As our estimated parameters fits very closely to the sample mean and
population sd under the normal distribution, we can deduce with
certainty that the MLE for mean and sd of a random distribution is
approximately the sample mean and population sd.

## MLE for the parameters $\beta_0$ and $\beta_1$ in logistic regression

In simple logistic regression, we have a numeric explanatory variable
$X$ and binary response variable $Y$ that takes one of two values, 0
(failure) or 1 (success). We suppose that
$P(Y=1|X=x) = p(x; \beta_0, \beta_1)$ for some function $p$ of the data
$x$ and two parameters $\beta_0$ and $\beta_1$, so that
$P(Y=0|X=x) = 1 - p(x; \beta_0, \beta_1)$.

Given the data $(x_1, y_1), \ldots, (x_n, y_n)$, where each
$y_i \in \{0, 1\}$, the probability of the data under the model is

$$f(y_1, \ldots, y_n | x_1, \ldots, x_n; \beta_0, \beta_1) = \prod_{i=1}^n p(x_i; \beta_0, \beta_1)^{y_i} (1 - p(x_i; \beta_0, \beta_1))^{1-y_i}$$

A *logistic transformation* maps $p \in [0, 1]$ to
$\log\left(\frac{p}{1-p}\right)$, whose range is the entire real line.
We define $p(x; \beta_0, \beta_1)$ implicitly by requiring its logistic
transformation to be linear:

$$\log\left(\frac{p(x; \beta_0, \beta_1)}{1-p(x; \beta_0, \beta_1)}\right) = \beta_0 + \beta_1 x$$

Solving for $p(x; \beta_0, \beta_1)$ gives

$$p(x; \beta_0, \beta_1) = \frac{1}{1 + \exp(-(\beta_0 + \beta_1 x))}$$

which is called the sigmoid function.

``` r
## Function for p(x;par) where par = c(beta0, beta1)
sigmoid = function(par, x)
{
  return ( 1/(1 + exp(-par[1] - par[2]*x)) )
}
```

The likelihood of $(\beta_1, \beta_1)$ given the data is then

$$L(\beta_0, \beta_1; x_1, \ldots, x_n, y_1, \ldots, y_n) = \prod_{i=1}^n \left(\frac{1}{1 + \exp(-(\beta_0 + \beta_1 x_i))}\right)^{y_i} \left(1 - \frac{1}{1 + \exp(-(\beta_0 + \beta_1 x_i))}\right)^{1-y_i}$$

and the log likelihood is (after a few lines of work)
$$l(\beta_0, \beta_1; x_1, \ldots, x_n, y_1, \ldots, y_n) = -\sum_{i=1}^n \log(1 + \exp(\beta_0 + \beta_1 x_i)) + \sum_{i=1}^n y_i (\beta_0 + \beta_1 x_i)$$

``` r
Log.Lik = function(par, x, y)
{
  p = sigmoid(par, x)
  return ( -sum(y*log(p) + (1-y)*log(1-p)) )
}
```

Consider the `menarche` data frame in the `MASS` package
(`require("MASS"); ?menarche`). It gives proportions of girls at various
ages who have reached menarche.

    ##      Age Total Menarche
    ## 1   9.21   376        0
    ## 2  10.21   200        0
    ## 3  10.58    93        0
    ## 4  10.83   120        2
    ## 5  11.08    90        2
    ## 6  11.33    88        5
    ## 7  11.58   105       10
    ## 8  11.83   111       17
    ## 9  12.08   100       16
    ## 10 12.33    93       29
    ## 11 12.58   100       39
    ## 12 12.83   108       51
    ## 13 13.08    99       47
    ## 14 13.33   106       67
    ## 15 13.58   105       81
    ## 16 13.83   117       88
    ## 17 14.08    98       79
    ## 18 14.33    97       90
    ## 19 14.58   120      113
    ## 20 14.83   102       95
    ## 21 15.08   122      117
    ## 22 15.33   111      107
    ## 23 15.58    94       92
    ## 24 15.83   114      112
    ## 25 17.58  1049     1049

The first row says “0 out of 376 girls with average age 9.21 have
reached menarche.” The tenth row says “29 out of 93 girls with average
age 12.33 have reached menarche.” The last row says “1049 out of 1049
girls with average age 17.58 have reached menarche.”

Here I’ll make a second data frame called `menarche.cases` from
`menarche` that gives one line for each girl in the study indicating her
age and whether (1) or not (0) she has reached menarche.

``` r
success.indices = rep(x=seq_len(nrow(menarche)), times=menarche$Menarche)
success.ages = menarche$Age[success.indices]
success = data.frame(age=success.ages, reached.menarche=1)
failure.indices = rep(x=seq_len(nrow(menarche)), times=menarche$Total - menarche$Menarche)
failure.ages = menarche$Age[failure.indices]
failure = data.frame(age=failure.ages, reached.menarche=0)
menarche.cases = rbind(success, failure)
menarche.cases = menarche.cases[order(menarche.cases$age), ]
rownames(menarche.cases) = NULL # Remove incorrectly ordered rownames; they get restored correctly.
menarche.cases
```

    ##        age reached.menarche
    ## 1     9.21                0
    ## 2     9.21                0
    ## 3     9.21                0
    ## 4     9.21                0
    ## 5     9.21                0
    ## 6     9.21                0
    ## 7     9.21                0
    ## 8     9.21                0
    ## 9     9.21                0
    ## 10    9.21                0
    ## 11    9.21                0
    ## 12    9.21                0
    ## 13    9.21                0
    ## 14    9.21                0
    ## 15    9.21                0
    ## 16    9.21                0
    ## 17    9.21                0
    ## 18    9.21                0
    ## 19    9.21                0
    ## 20    9.21                0
    ## 21    9.21                0
    ## 22    9.21                0
    ## 23    9.21                0
    ## 24    9.21                0
    ## 25    9.21                0
    ## 26    9.21                0
    ## 27    9.21                0
    ## 28    9.21                0
    ## 29    9.21                0
    ## 30    9.21                0
    ## 31    9.21                0
    ## 32    9.21                0
    ## 33    9.21                0
    ## 34    9.21                0
    ## 35    9.21                0
    ## 36    9.21                0
    ## 37    9.21                0
    ## 38    9.21                0
    ## 39    9.21                0
    ## 40    9.21                0
    ## 41    9.21                0
    ## 42    9.21                0
    ## 43    9.21                0
    ## 44    9.21                0
    ## 45    9.21                0
    ## 46    9.21                0
    ## 47    9.21                0
    ## 48    9.21                0
    ## 49    9.21                0
    ## 50    9.21                0
    ## 51    9.21                0
    ## 52    9.21                0
    ## 53    9.21                0
    ## 54    9.21                0
    ## 55    9.21                0
    ## 56    9.21                0
    ## 57    9.21                0
    ## 58    9.21                0
    ## 59    9.21                0
    ## 60    9.21                0
    ## 61    9.21                0
    ## 62    9.21                0
    ## 63    9.21                0
    ## 64    9.21                0
    ## 65    9.21                0
    ## 66    9.21                0
    ## 67    9.21                0
    ## 68    9.21                0
    ## 69    9.21                0
    ## 70    9.21                0
    ## 71    9.21                0
    ## 72    9.21                0
    ## 73    9.21                0
    ## 74    9.21                0
    ## 75    9.21                0
    ## 76    9.21                0
    ## 77    9.21                0
    ## 78    9.21                0
    ## 79    9.21                0
    ## 80    9.21                0
    ## 81    9.21                0
    ## 82    9.21                0
    ## 83    9.21                0
    ## 84    9.21                0
    ## 85    9.21                0
    ## 86    9.21                0
    ## 87    9.21                0
    ## 88    9.21                0
    ## 89    9.21                0
    ## 90    9.21                0
    ## 91    9.21                0
    ## 92    9.21                0
    ## 93    9.21                0
    ## 94    9.21                0
    ## 95    9.21                0
    ## 96    9.21                0
    ## 97    9.21                0
    ## 98    9.21                0
    ## 99    9.21                0
    ## 100   9.21                0
    ## 101   9.21                0
    ## 102   9.21                0
    ## 103   9.21                0
    ## 104   9.21                0
    ## 105   9.21                0
    ## 106   9.21                0
    ## 107   9.21                0
    ## 108   9.21                0
    ## 109   9.21                0
    ## 110   9.21                0
    ## 111   9.21                0
    ## 112   9.21                0
    ## 113   9.21                0
    ## 114   9.21                0
    ## 115   9.21                0
    ## 116   9.21                0
    ## 117   9.21                0
    ## 118   9.21                0
    ## 119   9.21                0
    ## 120   9.21                0
    ## 121   9.21                0
    ## 122   9.21                0
    ## 123   9.21                0
    ## 124   9.21                0
    ## 125   9.21                0
    ## 126   9.21                0
    ## 127   9.21                0
    ## 128   9.21                0
    ## 129   9.21                0
    ## 130   9.21                0
    ## 131   9.21                0
    ## 132   9.21                0
    ## 133   9.21                0
    ## 134   9.21                0
    ## 135   9.21                0
    ## 136   9.21                0
    ## 137   9.21                0
    ## 138   9.21                0
    ## 139   9.21                0
    ## 140   9.21                0
    ## 141   9.21                0
    ## 142   9.21                0
    ## 143   9.21                0
    ## 144   9.21                0
    ## 145   9.21                0
    ## 146   9.21                0
    ## 147   9.21                0
    ## 148   9.21                0
    ## 149   9.21                0
    ## 150   9.21                0
    ## 151   9.21                0
    ## 152   9.21                0
    ## 153   9.21                0
    ## 154   9.21                0
    ## 155   9.21                0
    ## 156   9.21                0
    ## 157   9.21                0
    ## 158   9.21                0
    ## 159   9.21                0
    ## 160   9.21                0
    ## 161   9.21                0
    ## 162   9.21                0
    ## 163   9.21                0
    ## 164   9.21                0
    ## 165   9.21                0
    ## 166   9.21                0
    ## 167   9.21                0
    ## 168   9.21                0
    ## 169   9.21                0
    ## 170   9.21                0
    ## 171   9.21                0
    ## 172   9.21                0
    ## 173   9.21                0
    ## 174   9.21                0
    ## 175   9.21                0
    ## 176   9.21                0
    ## 177   9.21                0
    ## 178   9.21                0
    ## 179   9.21                0
    ## 180   9.21                0
    ## 181   9.21                0
    ## 182   9.21                0
    ## 183   9.21                0
    ## 184   9.21                0
    ## 185   9.21                0
    ## 186   9.21                0
    ## 187   9.21                0
    ## 188   9.21                0
    ## 189   9.21                0
    ## 190   9.21                0
    ## 191   9.21                0
    ## 192   9.21                0
    ## 193   9.21                0
    ## 194   9.21                0
    ## 195   9.21                0
    ## 196   9.21                0
    ## 197   9.21                0
    ## 198   9.21                0
    ## 199   9.21                0
    ## 200   9.21                0
    ## 201   9.21                0
    ## 202   9.21                0
    ## 203   9.21                0
    ## 204   9.21                0
    ## 205   9.21                0
    ## 206   9.21                0
    ## 207   9.21                0
    ## 208   9.21                0
    ## 209   9.21                0
    ## 210   9.21                0
    ## 211   9.21                0
    ## 212   9.21                0
    ## 213   9.21                0
    ## 214   9.21                0
    ## 215   9.21                0
    ## 216   9.21                0
    ## 217   9.21                0
    ## 218   9.21                0
    ## 219   9.21                0
    ## 220   9.21                0
    ## 221   9.21                0
    ## 222   9.21                0
    ## 223   9.21                0
    ## 224   9.21                0
    ## 225   9.21                0
    ## 226   9.21                0
    ## 227   9.21                0
    ## 228   9.21                0
    ## 229   9.21                0
    ## 230   9.21                0
    ## 231   9.21                0
    ## 232   9.21                0
    ## 233   9.21                0
    ## 234   9.21                0
    ## 235   9.21                0
    ## 236   9.21                0
    ## 237   9.21                0
    ## 238   9.21                0
    ## 239   9.21                0
    ## 240   9.21                0
    ## 241   9.21                0
    ## 242   9.21                0
    ## 243   9.21                0
    ## 244   9.21                0
    ## 245   9.21                0
    ## 246   9.21                0
    ## 247   9.21                0
    ## 248   9.21                0
    ## 249   9.21                0
    ## 250   9.21                0
    ## 251   9.21                0
    ## 252   9.21                0
    ## 253   9.21                0
    ## 254   9.21                0
    ## 255   9.21                0
    ## 256   9.21                0
    ## 257   9.21                0
    ## 258   9.21                0
    ## 259   9.21                0
    ## 260   9.21                0
    ## 261   9.21                0
    ## 262   9.21                0
    ## 263   9.21                0
    ## 264   9.21                0
    ## 265   9.21                0
    ## 266   9.21                0
    ## 267   9.21                0
    ## 268   9.21                0
    ## 269   9.21                0
    ## 270   9.21                0
    ## 271   9.21                0
    ## 272   9.21                0
    ## 273   9.21                0
    ## 274   9.21                0
    ## 275   9.21                0
    ## 276   9.21                0
    ## 277   9.21                0
    ## 278   9.21                0
    ## 279   9.21                0
    ## 280   9.21                0
    ## 281   9.21                0
    ## 282   9.21                0
    ## 283   9.21                0
    ## 284   9.21                0
    ## 285   9.21                0
    ## 286   9.21                0
    ## 287   9.21                0
    ## 288   9.21                0
    ## 289   9.21                0
    ## 290   9.21                0
    ## 291   9.21                0
    ## 292   9.21                0
    ## 293   9.21                0
    ## 294   9.21                0
    ## 295   9.21                0
    ## 296   9.21                0
    ## 297   9.21                0
    ## 298   9.21                0
    ## 299   9.21                0
    ## 300   9.21                0
    ## 301   9.21                0
    ## 302   9.21                0
    ## 303   9.21                0
    ## 304   9.21                0
    ## 305   9.21                0
    ## 306   9.21                0
    ## 307   9.21                0
    ## 308   9.21                0
    ## 309   9.21                0
    ## 310   9.21                0
    ## 311   9.21                0
    ## 312   9.21                0
    ## 313   9.21                0
    ## 314   9.21                0
    ## 315   9.21                0
    ## 316   9.21                0
    ## 317   9.21                0
    ## 318   9.21                0
    ## 319   9.21                0
    ## 320   9.21                0
    ## 321   9.21                0
    ## 322   9.21                0
    ## 323   9.21                0
    ## 324   9.21                0
    ## 325   9.21                0
    ## 326   9.21                0
    ## 327   9.21                0
    ## 328   9.21                0
    ## 329   9.21                0
    ## 330   9.21                0
    ## 331   9.21                0
    ## 332   9.21                0
    ## 333   9.21                0
    ## 334   9.21                0
    ## 335   9.21                0
    ## 336   9.21                0
    ## 337   9.21                0
    ## 338   9.21                0
    ## 339   9.21                0
    ## 340   9.21                0
    ## 341   9.21                0
    ## 342   9.21                0
    ## 343   9.21                0
    ## 344   9.21                0
    ## 345   9.21                0
    ## 346   9.21                0
    ## 347   9.21                0
    ## 348   9.21                0
    ## 349   9.21                0
    ## 350   9.21                0
    ## 351   9.21                0
    ## 352   9.21                0
    ## 353   9.21                0
    ## 354   9.21                0
    ## 355   9.21                0
    ## 356   9.21                0
    ## 357   9.21                0
    ## 358   9.21                0
    ## 359   9.21                0
    ## 360   9.21                0
    ## 361   9.21                0
    ## 362   9.21                0
    ## 363   9.21                0
    ## 364   9.21                0
    ## 365   9.21                0
    ## 366   9.21                0
    ## 367   9.21                0
    ## 368   9.21                0
    ## 369   9.21                0
    ## 370   9.21                0
    ## 371   9.21                0
    ## 372   9.21                0
    ## 373   9.21                0
    ## 374   9.21                0
    ## 375   9.21                0
    ## 376   9.21                0
    ## 377  10.21                0
    ## 378  10.21                0
    ## 379  10.21                0
    ## 380  10.21                0
    ## 381  10.21                0
    ## 382  10.21                0
    ## 383  10.21                0
    ## 384  10.21                0
    ## 385  10.21                0
    ## 386  10.21                0
    ## 387  10.21                0
    ## 388  10.21                0
    ## 389  10.21                0
    ## 390  10.21                0
    ## 391  10.21                0
    ## 392  10.21                0
    ## 393  10.21                0
    ## 394  10.21                0
    ## 395  10.21                0
    ## 396  10.21                0
    ## 397  10.21                0
    ## 398  10.21                0
    ## 399  10.21                0
    ## 400  10.21                0
    ## 401  10.21                0
    ## 402  10.21                0
    ## 403  10.21                0
    ## 404  10.21                0
    ## 405  10.21                0
    ## 406  10.21                0
    ## 407  10.21                0
    ## 408  10.21                0
    ## 409  10.21                0
    ## 410  10.21                0
    ## 411  10.21                0
    ## 412  10.21                0
    ## 413  10.21                0
    ## 414  10.21                0
    ## 415  10.21                0
    ## 416  10.21                0
    ## 417  10.21                0
    ## 418  10.21                0
    ## 419  10.21                0
    ## 420  10.21                0
    ## 421  10.21                0
    ## 422  10.21                0
    ## 423  10.21                0
    ## 424  10.21                0
    ## 425  10.21                0
    ## 426  10.21                0
    ## 427  10.21                0
    ## 428  10.21                0
    ## 429  10.21                0
    ## 430  10.21                0
    ## 431  10.21                0
    ## 432  10.21                0
    ## 433  10.21                0
    ## 434  10.21                0
    ## 435  10.21                0
    ## 436  10.21                0
    ## 437  10.21                0
    ## 438  10.21                0
    ## 439  10.21                0
    ## 440  10.21                0
    ## 441  10.21                0
    ## 442  10.21                0
    ## 443  10.21                0
    ## 444  10.21                0
    ## 445  10.21                0
    ## 446  10.21                0
    ## 447  10.21                0
    ## 448  10.21                0
    ## 449  10.21                0
    ## 450  10.21                0
    ## 451  10.21                0
    ## 452  10.21                0
    ## 453  10.21                0
    ## 454  10.21                0
    ## 455  10.21                0
    ## 456  10.21                0
    ## 457  10.21                0
    ## 458  10.21                0
    ## 459  10.21                0
    ## 460  10.21                0
    ## 461  10.21                0
    ## 462  10.21                0
    ## 463  10.21                0
    ## 464  10.21                0
    ## 465  10.21                0
    ## 466  10.21                0
    ## 467  10.21                0
    ## 468  10.21                0
    ## 469  10.21                0
    ## 470  10.21                0
    ## 471  10.21                0
    ## 472  10.21                0
    ## 473  10.21                0
    ## 474  10.21                0
    ## 475  10.21                0
    ## 476  10.21                0
    ## 477  10.21                0
    ## 478  10.21                0
    ## 479  10.21                0
    ## 480  10.21                0
    ## 481  10.21                0
    ## 482  10.21                0
    ## 483  10.21                0
    ## 484  10.21                0
    ## 485  10.21                0
    ## 486  10.21                0
    ## 487  10.21                0
    ## 488  10.21                0
    ## 489  10.21                0
    ## 490  10.21                0
    ## 491  10.21                0
    ## 492  10.21                0
    ## 493  10.21                0
    ## 494  10.21                0
    ## 495  10.21                0
    ## 496  10.21                0
    ## 497  10.21                0
    ## 498  10.21                0
    ## 499  10.21                0
    ## 500  10.21                0
    ## 501  10.21                0
    ## 502  10.21                0
    ## 503  10.21                0
    ## 504  10.21                0
    ## 505  10.21                0
    ## 506  10.21                0
    ## 507  10.21                0
    ## 508  10.21                0
    ## 509  10.21                0
    ## 510  10.21                0
    ## 511  10.21                0
    ## 512  10.21                0
    ## 513  10.21                0
    ## 514  10.21                0
    ## 515  10.21                0
    ## 516  10.21                0
    ## 517  10.21                0
    ## 518  10.21                0
    ## 519  10.21                0
    ## 520  10.21                0
    ## 521  10.21                0
    ## 522  10.21                0
    ## 523  10.21                0
    ## 524  10.21                0
    ## 525  10.21                0
    ## 526  10.21                0
    ## 527  10.21                0
    ## 528  10.21                0
    ## 529  10.21                0
    ## 530  10.21                0
    ## 531  10.21                0
    ## 532  10.21                0
    ## 533  10.21                0
    ## 534  10.21                0
    ## 535  10.21                0
    ## 536  10.21                0
    ## 537  10.21                0
    ## 538  10.21                0
    ## 539  10.21                0
    ## 540  10.21                0
    ## 541  10.21                0
    ## 542  10.21                0
    ## 543  10.21                0
    ## 544  10.21                0
    ## 545  10.21                0
    ## 546  10.21                0
    ## 547  10.21                0
    ## 548  10.21                0
    ## 549  10.21                0
    ## 550  10.21                0
    ## 551  10.21                0
    ## 552  10.21                0
    ## 553  10.21                0
    ## 554  10.21                0
    ## 555  10.21                0
    ## 556  10.21                0
    ## 557  10.21                0
    ## 558  10.21                0
    ## 559  10.21                0
    ## 560  10.21                0
    ## 561  10.21                0
    ## 562  10.21                0
    ## 563  10.21                0
    ## 564  10.21                0
    ## 565  10.21                0
    ## 566  10.21                0
    ## 567  10.21                0
    ## 568  10.21                0
    ## 569  10.21                0
    ## 570  10.21                0
    ## 571  10.21                0
    ## 572  10.21                0
    ## 573  10.21                0
    ## 574  10.21                0
    ## 575  10.21                0
    ## 576  10.21                0
    ## 577  10.58                0
    ## 578  10.58                0
    ## 579  10.58                0
    ## 580  10.58                0
    ## 581  10.58                0
    ## 582  10.58                0
    ## 583  10.58                0
    ## 584  10.58                0
    ## 585  10.58                0
    ## 586  10.58                0
    ## 587  10.58                0
    ## 588  10.58                0
    ## 589  10.58                0
    ## 590  10.58                0
    ## 591  10.58                0
    ## 592  10.58                0
    ## 593  10.58                0
    ## 594  10.58                0
    ## 595  10.58                0
    ## 596  10.58                0
    ## 597  10.58                0
    ## 598  10.58                0
    ## 599  10.58                0
    ## 600  10.58                0
    ## 601  10.58                0
    ## 602  10.58                0
    ## 603  10.58                0
    ## 604  10.58                0
    ## 605  10.58                0
    ## 606  10.58                0
    ## 607  10.58                0
    ## 608  10.58                0
    ## 609  10.58                0
    ## 610  10.58                0
    ## 611  10.58                0
    ## 612  10.58                0
    ## 613  10.58                0
    ## 614  10.58                0
    ## 615  10.58                0
    ## 616  10.58                0
    ## 617  10.58                0
    ## 618  10.58                0
    ## 619  10.58                0
    ## 620  10.58                0
    ## 621  10.58                0
    ## 622  10.58                0
    ## 623  10.58                0
    ## 624  10.58                0
    ## 625  10.58                0
    ## 626  10.58                0
    ## 627  10.58                0
    ## 628  10.58                0
    ## 629  10.58                0
    ## 630  10.58                0
    ## 631  10.58                0
    ## 632  10.58                0
    ## 633  10.58                0
    ## 634  10.58                0
    ## 635  10.58                0
    ## 636  10.58                0
    ## 637  10.58                0
    ## 638  10.58                0
    ## 639  10.58                0
    ## 640  10.58                0
    ## 641  10.58                0
    ## 642  10.58                0
    ## 643  10.58                0
    ## 644  10.58                0
    ## 645  10.58                0
    ## 646  10.58                0
    ## 647  10.58                0
    ## 648  10.58                0
    ## 649  10.58                0
    ## 650  10.58                0
    ## 651  10.58                0
    ## 652  10.58                0
    ## 653  10.58                0
    ## 654  10.58                0
    ## 655  10.58                0
    ## 656  10.58                0
    ## 657  10.58                0
    ## 658  10.58                0
    ## 659  10.58                0
    ## 660  10.58                0
    ## 661  10.58                0
    ## 662  10.58                0
    ## 663  10.58                0
    ## 664  10.58                0
    ## 665  10.58                0
    ## 666  10.58                0
    ## 667  10.58                0
    ## 668  10.58                0
    ## 669  10.58                0
    ## 670  10.83                1
    ## 671  10.83                1
    ## 672  10.83                0
    ## 673  10.83                0
    ## 674  10.83                0
    ## 675  10.83                0
    ## 676  10.83                0
    ## 677  10.83                0
    ## 678  10.83                0
    ## 679  10.83                0
    ## 680  10.83                0
    ## 681  10.83                0
    ## 682  10.83                0
    ## 683  10.83                0
    ## 684  10.83                0
    ## 685  10.83                0
    ## 686  10.83                0
    ## 687  10.83                0
    ## 688  10.83                0
    ## 689  10.83                0
    ## 690  10.83                0
    ## 691  10.83                0
    ## 692  10.83                0
    ## 693  10.83                0
    ## 694  10.83                0
    ## 695  10.83                0
    ## 696  10.83                0
    ## 697  10.83                0
    ## 698  10.83                0
    ## 699  10.83                0
    ## 700  10.83                0
    ## 701  10.83                0
    ## 702  10.83                0
    ## 703  10.83                0
    ## 704  10.83                0
    ## 705  10.83                0
    ## 706  10.83                0
    ## 707  10.83                0
    ## 708  10.83                0
    ## 709  10.83                0
    ## 710  10.83                0
    ## 711  10.83                0
    ## 712  10.83                0
    ## 713  10.83                0
    ## 714  10.83                0
    ## 715  10.83                0
    ## 716  10.83                0
    ## 717  10.83                0
    ## 718  10.83                0
    ## 719  10.83                0
    ## 720  10.83                0
    ## 721  10.83                0
    ## 722  10.83                0
    ## 723  10.83                0
    ## 724  10.83                0
    ## 725  10.83                0
    ## 726  10.83                0
    ## 727  10.83                0
    ## 728  10.83                0
    ## 729  10.83                0
    ## 730  10.83                0
    ## 731  10.83                0
    ## 732  10.83                0
    ## 733  10.83                0
    ## 734  10.83                0
    ## 735  10.83                0
    ## 736  10.83                0
    ## 737  10.83                0
    ## 738  10.83                0
    ## 739  10.83                0
    ## 740  10.83                0
    ## 741  10.83                0
    ## 742  10.83                0
    ## 743  10.83                0
    ## 744  10.83                0
    ## 745  10.83                0
    ## 746  10.83                0
    ## 747  10.83                0
    ## 748  10.83                0
    ## 749  10.83                0
    ## 750  10.83                0
    ## 751  10.83                0
    ## 752  10.83                0
    ## 753  10.83                0
    ## 754  10.83                0
    ## 755  10.83                0
    ## 756  10.83                0
    ## 757  10.83                0
    ## 758  10.83                0
    ## 759  10.83                0
    ## 760  10.83                0
    ## 761  10.83                0
    ## 762  10.83                0
    ## 763  10.83                0
    ## 764  10.83                0
    ## 765  10.83                0
    ## 766  10.83                0
    ## 767  10.83                0
    ## 768  10.83                0
    ## 769  10.83                0
    ## 770  10.83                0
    ## 771  10.83                0
    ## 772  10.83                0
    ## 773  10.83                0
    ## 774  10.83                0
    ## 775  10.83                0
    ## 776  10.83                0
    ## 777  10.83                0
    ## 778  10.83                0
    ## 779  10.83                0
    ## 780  10.83                0
    ## 781  10.83                0
    ## 782  10.83                0
    ## 783  10.83                0
    ## 784  10.83                0
    ## 785  10.83                0
    ## 786  10.83                0
    ## 787  10.83                0
    ## 788  10.83                0
    ## 789  10.83                0
    ## 790  11.08                1
    ## 791  11.08                1
    ## 792  11.08                0
    ## 793  11.08                0
    ## 794  11.08                0
    ## 795  11.08                0
    ## 796  11.08                0
    ## 797  11.08                0
    ## 798  11.08                0
    ## 799  11.08                0
    ## 800  11.08                0
    ## 801  11.08                0
    ## 802  11.08                0
    ## 803  11.08                0
    ## 804  11.08                0
    ## 805  11.08                0
    ## 806  11.08                0
    ## 807  11.08                0
    ## 808  11.08                0
    ## 809  11.08                0
    ## 810  11.08                0
    ## 811  11.08                0
    ## 812  11.08                0
    ## 813  11.08                0
    ## 814  11.08                0
    ## 815  11.08                0
    ## 816  11.08                0
    ## 817  11.08                0
    ## 818  11.08                0
    ## 819  11.08                0
    ## 820  11.08                0
    ## 821  11.08                0
    ## 822  11.08                0
    ## 823  11.08                0
    ## 824  11.08                0
    ## 825  11.08                0
    ## 826  11.08                0
    ## 827  11.08                0
    ## 828  11.08                0
    ## 829  11.08                0
    ## 830  11.08                0
    ## 831  11.08                0
    ## 832  11.08                0
    ## 833  11.08                0
    ## 834  11.08                0
    ## 835  11.08                0
    ## 836  11.08                0
    ## 837  11.08                0
    ## 838  11.08                0
    ## 839  11.08                0
    ## 840  11.08                0
    ## 841  11.08                0
    ## 842  11.08                0
    ## 843  11.08                0
    ## 844  11.08                0
    ## 845  11.08                0
    ## 846  11.08                0
    ## 847  11.08                0
    ## 848  11.08                0
    ## 849  11.08                0
    ## 850  11.08                0
    ## 851  11.08                0
    ## 852  11.08                0
    ## 853  11.08                0
    ## 854  11.08                0
    ## 855  11.08                0
    ## 856  11.08                0
    ## 857  11.08                0
    ## 858  11.08                0
    ## 859  11.08                0
    ## 860  11.08                0
    ## 861  11.08                0
    ## 862  11.08                0
    ## 863  11.08                0
    ## 864  11.08                0
    ## 865  11.08                0
    ## 866  11.08                0
    ## 867  11.08                0
    ## 868  11.08                0
    ## 869  11.08                0
    ## 870  11.08                0
    ## 871  11.08                0
    ## 872  11.08                0
    ## 873  11.08                0
    ## 874  11.08                0
    ## 875  11.08                0
    ## 876  11.08                0
    ## 877  11.08                0
    ## 878  11.08                0
    ## 879  11.08                0
    ## 880  11.33                1
    ## 881  11.33                1
    ## 882  11.33                1
    ## 883  11.33                1
    ## 884  11.33                1
    ## 885  11.33                0
    ## 886  11.33                0
    ## 887  11.33                0
    ## 888  11.33                0
    ## 889  11.33                0
    ## 890  11.33                0
    ## 891  11.33                0
    ## 892  11.33                0
    ## 893  11.33                0
    ## 894  11.33                0
    ## 895  11.33                0
    ## 896  11.33                0
    ## 897  11.33                0
    ## 898  11.33                0
    ## 899  11.33                0
    ## 900  11.33                0
    ## 901  11.33                0
    ## 902  11.33                0
    ## 903  11.33                0
    ## 904  11.33                0
    ## 905  11.33                0
    ## 906  11.33                0
    ## 907  11.33                0
    ## 908  11.33                0
    ## 909  11.33                0
    ## 910  11.33                0
    ## 911  11.33                0
    ## 912  11.33                0
    ## 913  11.33                0
    ## 914  11.33                0
    ## 915  11.33                0
    ## 916  11.33                0
    ## 917  11.33                0
    ## 918  11.33                0
    ## 919  11.33                0
    ## 920  11.33                0
    ## 921  11.33                0
    ## 922  11.33                0
    ## 923  11.33                0
    ## 924  11.33                0
    ## 925  11.33                0
    ## 926  11.33                0
    ## 927  11.33                0
    ## 928  11.33                0
    ## 929  11.33                0
    ## 930  11.33                0
    ## 931  11.33                0
    ## 932  11.33                0
    ## 933  11.33                0
    ## 934  11.33                0
    ## 935  11.33                0
    ## 936  11.33                0
    ## 937  11.33                0
    ## 938  11.33                0
    ## 939  11.33                0
    ## 940  11.33                0
    ## 941  11.33                0
    ## 942  11.33                0
    ## 943  11.33                0
    ## 944  11.33                0
    ## 945  11.33                0
    ## 946  11.33                0
    ## 947  11.33                0
    ## 948  11.33                0
    ## 949  11.33                0
    ## 950  11.33                0
    ## 951  11.33                0
    ## 952  11.33                0
    ## 953  11.33                0
    ## 954  11.33                0
    ## 955  11.33                0
    ## 956  11.33                0
    ## 957  11.33                0
    ## 958  11.33                0
    ## 959  11.33                0
    ## 960  11.33                0
    ## 961  11.33                0
    ## 962  11.33                0
    ## 963  11.33                0
    ## 964  11.33                0
    ## 965  11.33                0
    ## 966  11.33                0
    ## 967  11.33                0
    ## 968  11.58                1
    ## 969  11.58                1
    ## 970  11.58                1
    ## 971  11.58                1
    ## 972  11.58                1
    ## 973  11.58                1
    ## 974  11.58                1
    ## 975  11.58                1
    ## 976  11.58                1
    ## 977  11.58                1
    ## 978  11.58                0
    ## 979  11.58                0
    ## 980  11.58                0
    ## 981  11.58                0
    ## 982  11.58                0
    ## 983  11.58                0
    ## 984  11.58                0
    ## 985  11.58                0
    ## 986  11.58                0
    ## 987  11.58                0
    ## 988  11.58                0
    ## 989  11.58                0
    ## 990  11.58                0
    ## 991  11.58                0
    ## 992  11.58                0
    ## 993  11.58                0
    ## 994  11.58                0
    ## 995  11.58                0
    ## 996  11.58                0
    ## 997  11.58                0
    ## 998  11.58                0
    ## 999  11.58                0
    ## 1000 11.58                0
    ## 1001 11.58                0
    ## 1002 11.58                0
    ## 1003 11.58                0
    ## 1004 11.58                0
    ## 1005 11.58                0
    ## 1006 11.58                0
    ## 1007 11.58                0
    ## 1008 11.58                0
    ## 1009 11.58                0
    ## 1010 11.58                0
    ## 1011 11.58                0
    ## 1012 11.58                0
    ## 1013 11.58                0
    ## 1014 11.58                0
    ## 1015 11.58                0
    ## 1016 11.58                0
    ## 1017 11.58                0
    ## 1018 11.58                0
    ## 1019 11.58                0
    ## 1020 11.58                0
    ## 1021 11.58                0
    ## 1022 11.58                0
    ## 1023 11.58                0
    ## 1024 11.58                0
    ## 1025 11.58                0
    ## 1026 11.58                0
    ## 1027 11.58                0
    ## 1028 11.58                0
    ## 1029 11.58                0
    ## 1030 11.58                0
    ## 1031 11.58                0
    ## 1032 11.58                0
    ## 1033 11.58                0
    ## 1034 11.58                0
    ## 1035 11.58                0
    ## 1036 11.58                0
    ## 1037 11.58                0
    ## 1038 11.58                0
    ## 1039 11.58                0
    ## 1040 11.58                0
    ## 1041 11.58                0
    ## 1042 11.58                0
    ## 1043 11.58                0
    ## 1044 11.58                0
    ## 1045 11.58                0
    ## 1046 11.58                0
    ## 1047 11.58                0
    ## 1048 11.58                0
    ## 1049 11.58                0
    ## 1050 11.58                0
    ## 1051 11.58                0
    ## 1052 11.58                0
    ## 1053 11.58                0
    ## 1054 11.58                0
    ## 1055 11.58                0
    ## 1056 11.58                0
    ## 1057 11.58                0
    ## 1058 11.58                0
    ## 1059 11.58                0
    ## 1060 11.58                0
    ## 1061 11.58                0
    ## 1062 11.58                0
    ## 1063 11.58                0
    ## 1064 11.58                0
    ## 1065 11.58                0
    ## 1066 11.58                0
    ## 1067 11.58                0
    ## 1068 11.58                0
    ## 1069 11.58                0
    ## 1070 11.58                0
    ## 1071 11.58                0
    ## 1072 11.58                0
    ## 1073 11.83                1
    ## 1074 11.83                1
    ## 1075 11.83                1
    ## 1076 11.83                1
    ## 1077 11.83                1
    ## 1078 11.83                1
    ## 1079 11.83                1
    ## 1080 11.83                1
    ## 1081 11.83                1
    ## 1082 11.83                1
    ## 1083 11.83                1
    ## 1084 11.83                1
    ## 1085 11.83                1
    ## 1086 11.83                1
    ## 1087 11.83                1
    ## 1088 11.83                1
    ## 1089 11.83                1
    ## 1090 11.83                0
    ## 1091 11.83                0
    ## 1092 11.83                0
    ## 1093 11.83                0
    ## 1094 11.83                0
    ## 1095 11.83                0
    ## 1096 11.83                0
    ## 1097 11.83                0
    ## 1098 11.83                0
    ## 1099 11.83                0
    ## 1100 11.83                0
    ## 1101 11.83                0
    ## 1102 11.83                0
    ## 1103 11.83                0
    ## 1104 11.83                0
    ## 1105 11.83                0
    ## 1106 11.83                0
    ## 1107 11.83                0
    ## 1108 11.83                0
    ## 1109 11.83                0
    ## 1110 11.83                0
    ## 1111 11.83                0
    ## 1112 11.83                0
    ## 1113 11.83                0
    ## 1114 11.83                0
    ## 1115 11.83                0
    ## 1116 11.83                0
    ## 1117 11.83                0
    ## 1118 11.83                0
    ## 1119 11.83                0
    ## 1120 11.83                0
    ## 1121 11.83                0
    ## 1122 11.83                0
    ## 1123 11.83                0
    ## 1124 11.83                0
    ## 1125 11.83                0
    ## 1126 11.83                0
    ## 1127 11.83                0
    ## 1128 11.83                0
    ## 1129 11.83                0
    ## 1130 11.83                0
    ## 1131 11.83                0
    ## 1132 11.83                0
    ## 1133 11.83                0
    ## 1134 11.83                0
    ## 1135 11.83                0
    ## 1136 11.83                0
    ## 1137 11.83                0
    ## 1138 11.83                0
    ## 1139 11.83                0
    ## 1140 11.83                0
    ## 1141 11.83                0
    ## 1142 11.83                0
    ## 1143 11.83                0
    ## 1144 11.83                0
    ## 1145 11.83                0
    ## 1146 11.83                0
    ## 1147 11.83                0
    ## 1148 11.83                0
    ## 1149 11.83                0
    ## 1150 11.83                0
    ## 1151 11.83                0
    ## 1152 11.83                0
    ## 1153 11.83                0
    ## 1154 11.83                0
    ## 1155 11.83                0
    ## 1156 11.83                0
    ## 1157 11.83                0
    ## 1158 11.83                0
    ## 1159 11.83                0
    ## 1160 11.83                0
    ## 1161 11.83                0
    ## 1162 11.83                0
    ## 1163 11.83                0
    ## 1164 11.83                0
    ## 1165 11.83                0
    ## 1166 11.83                0
    ## 1167 11.83                0
    ## 1168 11.83                0
    ## 1169 11.83                0
    ## 1170 11.83                0
    ## 1171 11.83                0
    ## 1172 11.83                0
    ## 1173 11.83                0
    ## 1174 11.83                0
    ## 1175 11.83                0
    ## 1176 11.83                0
    ## 1177 11.83                0
    ## 1178 11.83                0
    ## 1179 11.83                0
    ## 1180 11.83                0
    ## 1181 11.83                0
    ## 1182 11.83                0
    ## 1183 11.83                0
    ## 1184 12.08                1
    ## 1185 12.08                1
    ## 1186 12.08                1
    ## 1187 12.08                1
    ## 1188 12.08                1
    ## 1189 12.08                1
    ## 1190 12.08                1
    ## 1191 12.08                1
    ## 1192 12.08                1
    ## 1193 12.08                1
    ## 1194 12.08                1
    ## 1195 12.08                1
    ## 1196 12.08                1
    ## 1197 12.08                1
    ## 1198 12.08                1
    ## 1199 12.08                1
    ## 1200 12.08                0
    ## 1201 12.08                0
    ## 1202 12.08                0
    ## 1203 12.08                0
    ## 1204 12.08                0
    ## 1205 12.08                0
    ## 1206 12.08                0
    ## 1207 12.08                0
    ## 1208 12.08                0
    ## 1209 12.08                0
    ## 1210 12.08                0
    ## 1211 12.08                0
    ## 1212 12.08                0
    ## 1213 12.08                0
    ## 1214 12.08                0
    ## 1215 12.08                0
    ## 1216 12.08                0
    ## 1217 12.08                0
    ## 1218 12.08                0
    ## 1219 12.08                0
    ## 1220 12.08                0
    ## 1221 12.08                0
    ## 1222 12.08                0
    ## 1223 12.08                0
    ## 1224 12.08                0
    ## 1225 12.08                0
    ## 1226 12.08                0
    ## 1227 12.08                0
    ## 1228 12.08                0
    ## 1229 12.08                0
    ## 1230 12.08                0
    ## 1231 12.08                0
    ## 1232 12.08                0
    ## 1233 12.08                0
    ## 1234 12.08                0
    ## 1235 12.08                0
    ## 1236 12.08                0
    ## 1237 12.08                0
    ## 1238 12.08                0
    ## 1239 12.08                0
    ## 1240 12.08                0
    ## 1241 12.08                0
    ## 1242 12.08                0
    ## 1243 12.08                0
    ## 1244 12.08                0
    ## 1245 12.08                0
    ## 1246 12.08                0
    ## 1247 12.08                0
    ## 1248 12.08                0
    ## 1249 12.08                0
    ## 1250 12.08                0
    ## 1251 12.08                0
    ## 1252 12.08                0
    ## 1253 12.08                0
    ## 1254 12.08                0
    ## 1255 12.08                0
    ## 1256 12.08                0
    ## 1257 12.08                0
    ## 1258 12.08                0
    ## 1259 12.08                0
    ## 1260 12.08                0
    ## 1261 12.08                0
    ## 1262 12.08                0
    ## 1263 12.08                0
    ## 1264 12.08                0
    ## 1265 12.08                0
    ## 1266 12.08                0
    ## 1267 12.08                0
    ## 1268 12.08                0
    ## 1269 12.08                0
    ## 1270 12.08                0
    ## 1271 12.08                0
    ## 1272 12.08                0
    ## 1273 12.08                0
    ## 1274 12.08                0
    ## 1275 12.08                0
    ## 1276 12.08                0
    ## 1277 12.08                0
    ## 1278 12.08                0
    ## 1279 12.08                0
    ## 1280 12.08                0
    ## 1281 12.08                0
    ## 1282 12.08                0
    ## 1283 12.08                0
    ## 1284 12.33                1
    ## 1285 12.33                1
    ## 1286 12.33                1
    ## 1287 12.33                1
    ## 1288 12.33                1
    ## 1289 12.33                1
    ## 1290 12.33                1
    ## 1291 12.33                1
    ## 1292 12.33                1
    ## 1293 12.33                1
    ## 1294 12.33                1
    ## 1295 12.33                1
    ## 1296 12.33                1
    ## 1297 12.33                1
    ## 1298 12.33                1
    ## 1299 12.33                1
    ## 1300 12.33                1
    ## 1301 12.33                1
    ## 1302 12.33                1
    ## 1303 12.33                1
    ## 1304 12.33                1
    ## 1305 12.33                1
    ## 1306 12.33                1
    ## 1307 12.33                1
    ## 1308 12.33                1
    ## 1309 12.33                1
    ## 1310 12.33                1
    ## 1311 12.33                1
    ## 1312 12.33                1
    ## 1313 12.33                0
    ## 1314 12.33                0
    ## 1315 12.33                0
    ## 1316 12.33                0
    ## 1317 12.33                0
    ## 1318 12.33                0
    ## 1319 12.33                0
    ## 1320 12.33                0
    ## 1321 12.33                0
    ## 1322 12.33                0
    ## 1323 12.33                0
    ## 1324 12.33                0
    ## 1325 12.33                0
    ## 1326 12.33                0
    ## 1327 12.33                0
    ## 1328 12.33                0
    ## 1329 12.33                0
    ## 1330 12.33                0
    ## 1331 12.33                0
    ## 1332 12.33                0
    ## 1333 12.33                0
    ## 1334 12.33                0
    ## 1335 12.33                0
    ## 1336 12.33                0
    ## 1337 12.33                0
    ## 1338 12.33                0
    ## 1339 12.33                0
    ## 1340 12.33                0
    ## 1341 12.33                0
    ## 1342 12.33                0
    ## 1343 12.33                0
    ## 1344 12.33                0
    ## 1345 12.33                0
    ## 1346 12.33                0
    ## 1347 12.33                0
    ## 1348 12.33                0
    ## 1349 12.33                0
    ## 1350 12.33                0
    ## 1351 12.33                0
    ## 1352 12.33                0
    ## 1353 12.33                0
    ## 1354 12.33                0
    ## 1355 12.33                0
    ## 1356 12.33                0
    ## 1357 12.33                0
    ## 1358 12.33                0
    ## 1359 12.33                0
    ## 1360 12.33                0
    ## 1361 12.33                0
    ## 1362 12.33                0
    ## 1363 12.33                0
    ## 1364 12.33                0
    ## 1365 12.33                0
    ## 1366 12.33                0
    ## 1367 12.33                0
    ## 1368 12.33                0
    ## 1369 12.33                0
    ## 1370 12.33                0
    ## 1371 12.33                0
    ## 1372 12.33                0
    ## 1373 12.33                0
    ## 1374 12.33                0
    ## 1375 12.33                0
    ## 1376 12.33                0
    ## 1377 12.58                1
    ## 1378 12.58                1
    ## 1379 12.58                1
    ## 1380 12.58                1
    ## 1381 12.58                1
    ## 1382 12.58                1
    ## 1383 12.58                1
    ## 1384 12.58                1
    ## 1385 12.58                1
    ## 1386 12.58                1
    ## 1387 12.58                1
    ## 1388 12.58                1
    ## 1389 12.58                1
    ## 1390 12.58                1
    ## 1391 12.58                1
    ## 1392 12.58                1
    ## 1393 12.58                1
    ## 1394 12.58                1
    ## 1395 12.58                1
    ## 1396 12.58                1
    ## 1397 12.58                1
    ## 1398 12.58                1
    ## 1399 12.58                1
    ## 1400 12.58                1
    ## 1401 12.58                1
    ## 1402 12.58                1
    ## 1403 12.58                1
    ## 1404 12.58                1
    ## 1405 12.58                1
    ## 1406 12.58                1
    ## 1407 12.58                1
    ## 1408 12.58                1
    ## 1409 12.58                1
    ## 1410 12.58                1
    ## 1411 12.58                1
    ## 1412 12.58                1
    ## 1413 12.58                1
    ## 1414 12.58                1
    ## 1415 12.58                1
    ## 1416 12.58                0
    ## 1417 12.58                0
    ## 1418 12.58                0
    ## 1419 12.58                0
    ## 1420 12.58                0
    ## 1421 12.58                0
    ## 1422 12.58                0
    ## 1423 12.58                0
    ## 1424 12.58                0
    ## 1425 12.58                0
    ## 1426 12.58                0
    ## 1427 12.58                0
    ## 1428 12.58                0
    ## 1429 12.58                0
    ## 1430 12.58                0
    ## 1431 12.58                0
    ## 1432 12.58                0
    ## 1433 12.58                0
    ## 1434 12.58                0
    ## 1435 12.58                0
    ## 1436 12.58                0
    ## 1437 12.58                0
    ## 1438 12.58                0
    ## 1439 12.58                0
    ## 1440 12.58                0
    ## 1441 12.58                0
    ## 1442 12.58                0
    ## 1443 12.58                0
    ## 1444 12.58                0
    ## 1445 12.58                0
    ## 1446 12.58                0
    ## 1447 12.58                0
    ## 1448 12.58                0
    ## 1449 12.58                0
    ## 1450 12.58                0
    ## 1451 12.58                0
    ## 1452 12.58                0
    ## 1453 12.58                0
    ## 1454 12.58                0
    ## 1455 12.58                0
    ## 1456 12.58                0
    ## 1457 12.58                0
    ## 1458 12.58                0
    ## 1459 12.58                0
    ## 1460 12.58                0
    ## 1461 12.58                0
    ## 1462 12.58                0
    ## 1463 12.58                0
    ## 1464 12.58                0
    ## 1465 12.58                0
    ## 1466 12.58                0
    ## 1467 12.58                0
    ## 1468 12.58                0
    ## 1469 12.58                0
    ## 1470 12.58                0
    ## 1471 12.58                0
    ## 1472 12.58                0
    ## 1473 12.58                0
    ## 1474 12.58                0
    ## 1475 12.58                0
    ## 1476 12.58                0
    ## 1477 12.83                1
    ## 1478 12.83                1
    ## 1479 12.83                1
    ## 1480 12.83                1
    ## 1481 12.83                1
    ## 1482 12.83                1
    ## 1483 12.83                1
    ## 1484 12.83                1
    ## 1485 12.83                1
    ## 1486 12.83                1
    ## 1487 12.83                1
    ## 1488 12.83                1
    ## 1489 12.83                1
    ## 1490 12.83                1
    ## 1491 12.83                1
    ## 1492 12.83                1
    ## 1493 12.83                1
    ## 1494 12.83                1
    ## 1495 12.83                1
    ## 1496 12.83                1
    ## 1497 12.83                1
    ## 1498 12.83                1
    ## 1499 12.83                1
    ## 1500 12.83                1
    ## 1501 12.83                1
    ## 1502 12.83                1
    ## 1503 12.83                1
    ## 1504 12.83                1
    ## 1505 12.83                1
    ## 1506 12.83                1
    ## 1507 12.83                1
    ## 1508 12.83                1
    ## 1509 12.83                1
    ## 1510 12.83                1
    ## 1511 12.83                1
    ## 1512 12.83                1
    ## 1513 12.83                1
    ## 1514 12.83                1
    ## 1515 12.83                1
    ## 1516 12.83                1
    ## 1517 12.83                1
    ## 1518 12.83                1
    ## 1519 12.83                1
    ## 1520 12.83                1
    ## 1521 12.83                1
    ## 1522 12.83                1
    ## 1523 12.83                1
    ## 1524 12.83                1
    ## 1525 12.83                1
    ## 1526 12.83                1
    ## 1527 12.83                1
    ## 1528 12.83                0
    ## 1529 12.83                0
    ## 1530 12.83                0
    ## 1531 12.83                0
    ## 1532 12.83                0
    ## 1533 12.83                0
    ## 1534 12.83                0
    ## 1535 12.83                0
    ## 1536 12.83                0
    ## 1537 12.83                0
    ## 1538 12.83                0
    ## 1539 12.83                0
    ## 1540 12.83                0
    ## 1541 12.83                0
    ## 1542 12.83                0
    ## 1543 12.83                0
    ## 1544 12.83                0
    ## 1545 12.83                0
    ## 1546 12.83                0
    ## 1547 12.83                0
    ## 1548 12.83                0
    ## 1549 12.83                0
    ## 1550 12.83                0
    ## 1551 12.83                0
    ## 1552 12.83                0
    ## 1553 12.83                0
    ## 1554 12.83                0
    ## 1555 12.83                0
    ## 1556 12.83                0
    ## 1557 12.83                0
    ## 1558 12.83                0
    ## 1559 12.83                0
    ## 1560 12.83                0
    ## 1561 12.83                0
    ## 1562 12.83                0
    ## 1563 12.83                0
    ## 1564 12.83                0
    ## 1565 12.83                0
    ## 1566 12.83                0
    ## 1567 12.83                0
    ## 1568 12.83                0
    ## 1569 12.83                0
    ## 1570 12.83                0
    ## 1571 12.83                0
    ## 1572 12.83                0
    ## 1573 12.83                0
    ## 1574 12.83                0
    ## 1575 12.83                0
    ## 1576 12.83                0
    ## 1577 12.83                0
    ## 1578 12.83                0
    ## 1579 12.83                0
    ## 1580 12.83                0
    ## 1581 12.83                0
    ## 1582 12.83                0
    ## 1583 12.83                0
    ## 1584 12.83                0
    ## 1585 13.08                1
    ## 1586 13.08                1
    ## 1587 13.08                1
    ## 1588 13.08                1
    ## 1589 13.08                1
    ## 1590 13.08                1
    ## 1591 13.08                1
    ## 1592 13.08                1
    ## 1593 13.08                1
    ## 1594 13.08                1
    ## 1595 13.08                1
    ## 1596 13.08                1
    ## 1597 13.08                1
    ## 1598 13.08                1
    ## 1599 13.08                1
    ## 1600 13.08                1
    ## 1601 13.08                1
    ## 1602 13.08                1
    ## 1603 13.08                1
    ## 1604 13.08                1
    ## 1605 13.08                1
    ## 1606 13.08                1
    ## 1607 13.08                1
    ## 1608 13.08                1
    ## 1609 13.08                1
    ## 1610 13.08                1
    ## 1611 13.08                1
    ## 1612 13.08                1
    ## 1613 13.08                1
    ## 1614 13.08                1
    ## 1615 13.08                1
    ## 1616 13.08                1
    ## 1617 13.08                1
    ## 1618 13.08                1
    ## 1619 13.08                1
    ## 1620 13.08                1
    ## 1621 13.08                1
    ## 1622 13.08                1
    ## 1623 13.08                1
    ## 1624 13.08                1
    ## 1625 13.08                1
    ## 1626 13.08                1
    ## 1627 13.08                1
    ## 1628 13.08                1
    ## 1629 13.08                1
    ## 1630 13.08                1
    ## 1631 13.08                1
    ## 1632 13.08                0
    ## 1633 13.08                0
    ## 1634 13.08                0
    ## 1635 13.08                0
    ## 1636 13.08                0
    ## 1637 13.08                0
    ## 1638 13.08                0
    ## 1639 13.08                0
    ## 1640 13.08                0
    ## 1641 13.08                0
    ## 1642 13.08                0
    ## 1643 13.08                0
    ## 1644 13.08                0
    ## 1645 13.08                0
    ## 1646 13.08                0
    ## 1647 13.08                0
    ## 1648 13.08                0
    ## 1649 13.08                0
    ## 1650 13.08                0
    ## 1651 13.08                0
    ## 1652 13.08                0
    ## 1653 13.08                0
    ## 1654 13.08                0
    ## 1655 13.08                0
    ## 1656 13.08                0
    ## 1657 13.08                0
    ## 1658 13.08                0
    ## 1659 13.08                0
    ## 1660 13.08                0
    ## 1661 13.08                0
    ## 1662 13.08                0
    ## 1663 13.08                0
    ## 1664 13.08                0
    ## 1665 13.08                0
    ## 1666 13.08                0
    ## 1667 13.08                0
    ## 1668 13.08                0
    ## 1669 13.08                0
    ## 1670 13.08                0
    ## 1671 13.08                0
    ## 1672 13.08                0
    ## 1673 13.08                0
    ## 1674 13.08                0
    ## 1675 13.08                0
    ## 1676 13.08                0
    ## 1677 13.08                0
    ## 1678 13.08                0
    ## 1679 13.08                0
    ## 1680 13.08                0
    ## 1681 13.08                0
    ## 1682 13.08                0
    ## 1683 13.08                0
    ## 1684 13.33                1
    ## 1685 13.33                1
    ## 1686 13.33                1
    ## 1687 13.33                1
    ## 1688 13.33                1
    ## 1689 13.33                1
    ## 1690 13.33                1
    ## 1691 13.33                1
    ## 1692 13.33                1
    ## 1693 13.33                1
    ## 1694 13.33                1
    ## 1695 13.33                1
    ## 1696 13.33                1
    ## 1697 13.33                1
    ## 1698 13.33                1
    ## 1699 13.33                1
    ## 1700 13.33                1
    ## 1701 13.33                1
    ## 1702 13.33                1
    ## 1703 13.33                1
    ## 1704 13.33                1
    ## 1705 13.33                1
    ## 1706 13.33                1
    ## 1707 13.33                1
    ## 1708 13.33                1
    ## 1709 13.33                1
    ## 1710 13.33                1
    ## 1711 13.33                1
    ## 1712 13.33                1
    ## 1713 13.33                1
    ## 1714 13.33                1
    ## 1715 13.33                1
    ## 1716 13.33                1
    ## 1717 13.33                1
    ## 1718 13.33                1
    ## 1719 13.33                1
    ## 1720 13.33                1
    ## 1721 13.33                1
    ## 1722 13.33                1
    ## 1723 13.33                1
    ## 1724 13.33                1
    ## 1725 13.33                1
    ## 1726 13.33                1
    ## 1727 13.33                1
    ## 1728 13.33                1
    ## 1729 13.33                1
    ## 1730 13.33                1
    ## 1731 13.33                1
    ## 1732 13.33                1
    ## 1733 13.33                1
    ## 1734 13.33                1
    ## 1735 13.33                1
    ## 1736 13.33                1
    ## 1737 13.33                1
    ## 1738 13.33                1
    ## 1739 13.33                1
    ## 1740 13.33                1
    ## 1741 13.33                1
    ## 1742 13.33                1
    ## 1743 13.33                1
    ## 1744 13.33                1
    ## 1745 13.33                1
    ## 1746 13.33                1
    ## 1747 13.33                1
    ## 1748 13.33                1
    ## 1749 13.33                1
    ## 1750 13.33                1
    ## 1751 13.33                0
    ## 1752 13.33                0
    ## 1753 13.33                0
    ## 1754 13.33                0
    ## 1755 13.33                0
    ## 1756 13.33                0
    ## 1757 13.33                0
    ## 1758 13.33                0
    ## 1759 13.33                0
    ## 1760 13.33                0
    ## 1761 13.33                0
    ## 1762 13.33                0
    ## 1763 13.33                0
    ## 1764 13.33                0
    ## 1765 13.33                0
    ## 1766 13.33                0
    ## 1767 13.33                0
    ## 1768 13.33                0
    ## 1769 13.33                0
    ## 1770 13.33                0
    ## 1771 13.33                0
    ## 1772 13.33                0
    ## 1773 13.33                0
    ## 1774 13.33                0
    ## 1775 13.33                0
    ## 1776 13.33                0
    ## 1777 13.33                0
    ## 1778 13.33                0
    ## 1779 13.33                0
    ## 1780 13.33                0
    ## 1781 13.33                0
    ## 1782 13.33                0
    ## 1783 13.33                0
    ## 1784 13.33                0
    ## 1785 13.33                0
    ## 1786 13.33                0
    ## 1787 13.33                0
    ## 1788 13.33                0
    ## 1789 13.33                0
    ## 1790 13.58                1
    ## 1791 13.58                1
    ## 1792 13.58                1
    ## 1793 13.58                1
    ## 1794 13.58                1
    ## 1795 13.58                1
    ## 1796 13.58                1
    ## 1797 13.58                1
    ## 1798 13.58                1
    ## 1799 13.58                1
    ## 1800 13.58                1
    ## 1801 13.58                1
    ## 1802 13.58                1
    ## 1803 13.58                1
    ## 1804 13.58                1
    ## 1805 13.58                1
    ## 1806 13.58                1
    ## 1807 13.58                1
    ## 1808 13.58                1
    ## 1809 13.58                1
    ## 1810 13.58                1
    ## 1811 13.58                1
    ## 1812 13.58                1
    ## 1813 13.58                1
    ## 1814 13.58                1
    ## 1815 13.58                1
    ## 1816 13.58                1
    ## 1817 13.58                1
    ## 1818 13.58                1
    ## 1819 13.58                1
    ## 1820 13.58                1
    ## 1821 13.58                1
    ## 1822 13.58                1
    ## 1823 13.58                1
    ## 1824 13.58                1
    ## 1825 13.58                1
    ## 1826 13.58                1
    ## 1827 13.58                1
    ## 1828 13.58                1
    ## 1829 13.58                1
    ## 1830 13.58                1
    ## 1831 13.58                1
    ## 1832 13.58                1
    ## 1833 13.58                1
    ## 1834 13.58                1
    ## 1835 13.58                1
    ## 1836 13.58                1
    ## 1837 13.58                1
    ## 1838 13.58                1
    ## 1839 13.58                1
    ## 1840 13.58                1
    ## 1841 13.58                1
    ## 1842 13.58                1
    ## 1843 13.58                1
    ## 1844 13.58                1
    ## 1845 13.58                1
    ## 1846 13.58                1
    ## 1847 13.58                1
    ## 1848 13.58                1
    ## 1849 13.58                1
    ## 1850 13.58                1
    ## 1851 13.58                1
    ## 1852 13.58                1
    ## 1853 13.58                1
    ## 1854 13.58                1
    ## 1855 13.58                1
    ## 1856 13.58                1
    ## 1857 13.58                1
    ## 1858 13.58                1
    ## 1859 13.58                1
    ## 1860 13.58                1
    ## 1861 13.58                1
    ## 1862 13.58                1
    ## 1863 13.58                1
    ## 1864 13.58                1
    ## 1865 13.58                1
    ## 1866 13.58                1
    ## 1867 13.58                1
    ## 1868 13.58                1
    ## 1869 13.58                1
    ## 1870 13.58                1
    ## 1871 13.58                0
    ## 1872 13.58                0
    ## 1873 13.58                0
    ## 1874 13.58                0
    ## 1875 13.58                0
    ## 1876 13.58                0
    ## 1877 13.58                0
    ## 1878 13.58                0
    ## 1879 13.58                0
    ## 1880 13.58                0
    ## 1881 13.58                0
    ## 1882 13.58                0
    ## 1883 13.58                0
    ## 1884 13.58                0
    ## 1885 13.58                0
    ## 1886 13.58                0
    ## 1887 13.58                0
    ## 1888 13.58                0
    ## 1889 13.58                0
    ## 1890 13.58                0
    ## 1891 13.58                0
    ## 1892 13.58                0
    ## 1893 13.58                0
    ## 1894 13.58                0
    ## 1895 13.83                1
    ## 1896 13.83                1
    ## 1897 13.83                1
    ## 1898 13.83                1
    ## 1899 13.83                1
    ## 1900 13.83                1
    ## 1901 13.83                1
    ## 1902 13.83                1
    ## 1903 13.83                1
    ## 1904 13.83                1
    ## 1905 13.83                1
    ## 1906 13.83                1
    ## 1907 13.83                1
    ## 1908 13.83                1
    ## 1909 13.83                1
    ## 1910 13.83                1
    ## 1911 13.83                1
    ## 1912 13.83                1
    ## 1913 13.83                1
    ## 1914 13.83                1
    ## 1915 13.83                1
    ## 1916 13.83                1
    ## 1917 13.83                1
    ## 1918 13.83                1
    ## 1919 13.83                1
    ## 1920 13.83                1
    ## 1921 13.83                1
    ## 1922 13.83                1
    ## 1923 13.83                1
    ## 1924 13.83                1
    ## 1925 13.83                1
    ## 1926 13.83                1
    ## 1927 13.83                1
    ## 1928 13.83                1
    ## 1929 13.83                1
    ## 1930 13.83                1
    ## 1931 13.83                1
    ## 1932 13.83                1
    ## 1933 13.83                1
    ## 1934 13.83                1
    ## 1935 13.83                1
    ## 1936 13.83                1
    ## 1937 13.83                1
    ## 1938 13.83                1
    ## 1939 13.83                1
    ## 1940 13.83                1
    ## 1941 13.83                1
    ## 1942 13.83                1
    ## 1943 13.83                1
    ## 1944 13.83                1
    ## 1945 13.83                1
    ## 1946 13.83                1
    ## 1947 13.83                1
    ## 1948 13.83                1
    ## 1949 13.83                1
    ## 1950 13.83                1
    ## 1951 13.83                1
    ## 1952 13.83                1
    ## 1953 13.83                1
    ## 1954 13.83                1
    ## 1955 13.83                1
    ## 1956 13.83                1
    ## 1957 13.83                1
    ## 1958 13.83                1
    ## 1959 13.83                1
    ## 1960 13.83                1
    ## 1961 13.83                1
    ## 1962 13.83                1
    ## 1963 13.83                1
    ## 1964 13.83                1
    ## 1965 13.83                1
    ## 1966 13.83                1
    ## 1967 13.83                1
    ## 1968 13.83                1
    ## 1969 13.83                1
    ## 1970 13.83                1
    ## 1971 13.83                1
    ## 1972 13.83                1
    ## 1973 13.83                1
    ## 1974 13.83                1
    ## 1975 13.83                1
    ## 1976 13.83                1
    ## 1977 13.83                1
    ## 1978 13.83                1
    ## 1979 13.83                1
    ## 1980 13.83                1
    ## 1981 13.83                1
    ## 1982 13.83                1
    ## 1983 13.83                0
    ## 1984 13.83                0
    ## 1985 13.83                0
    ## 1986 13.83                0
    ## 1987 13.83                0
    ## 1988 13.83                0
    ## 1989 13.83                0
    ## 1990 13.83                0
    ## 1991 13.83                0
    ## 1992 13.83                0
    ## 1993 13.83                0
    ## 1994 13.83                0
    ## 1995 13.83                0
    ## 1996 13.83                0
    ## 1997 13.83                0
    ## 1998 13.83                0
    ## 1999 13.83                0
    ## 2000 13.83                0
    ## 2001 13.83                0
    ## 2002 13.83                0
    ## 2003 13.83                0
    ## 2004 13.83                0
    ## 2005 13.83                0
    ## 2006 13.83                0
    ## 2007 13.83                0
    ## 2008 13.83                0
    ## 2009 13.83                0
    ## 2010 13.83                0
    ## 2011 13.83                0
    ## 2012 14.08                1
    ## 2013 14.08                1
    ## 2014 14.08                1
    ## 2015 14.08                1
    ## 2016 14.08                1
    ## 2017 14.08                1
    ## 2018 14.08                1
    ## 2019 14.08                1
    ## 2020 14.08                1
    ## 2021 14.08                1
    ## 2022 14.08                1
    ## 2023 14.08                1
    ## 2024 14.08                1
    ## 2025 14.08                1
    ## 2026 14.08                1
    ## 2027 14.08                1
    ## 2028 14.08                1
    ## 2029 14.08                1
    ## 2030 14.08                1
    ## 2031 14.08                1
    ## 2032 14.08                1
    ## 2033 14.08                1
    ## 2034 14.08                1
    ## 2035 14.08                1
    ## 2036 14.08                1
    ## 2037 14.08                1
    ## 2038 14.08                1
    ## 2039 14.08                1
    ## 2040 14.08                1
    ## 2041 14.08                1
    ## 2042 14.08                1
    ## 2043 14.08                1
    ## 2044 14.08                1
    ## 2045 14.08                1
    ## 2046 14.08                1
    ## 2047 14.08                1
    ## 2048 14.08                1
    ## 2049 14.08                1
    ## 2050 14.08                1
    ## 2051 14.08                1
    ## 2052 14.08                1
    ## 2053 14.08                1
    ## 2054 14.08                1
    ## 2055 14.08                1
    ## 2056 14.08                1
    ## 2057 14.08                1
    ## 2058 14.08                1
    ## 2059 14.08                1
    ## 2060 14.08                1
    ## 2061 14.08                1
    ## 2062 14.08                1
    ## 2063 14.08                1
    ## 2064 14.08                1
    ## 2065 14.08                1
    ## 2066 14.08                1
    ## 2067 14.08                1
    ## 2068 14.08                1
    ## 2069 14.08                1
    ## 2070 14.08                1
    ## 2071 14.08                1
    ## 2072 14.08                1
    ## 2073 14.08                1
    ## 2074 14.08                1
    ## 2075 14.08                1
    ## 2076 14.08                1
    ## 2077 14.08                1
    ## 2078 14.08                1
    ## 2079 14.08                1
    ## 2080 14.08                1
    ## 2081 14.08                1
    ## 2082 14.08                1
    ## 2083 14.08                1
    ## 2084 14.08                1
    ## 2085 14.08                1
    ## 2086 14.08                1
    ## 2087 14.08                1
    ## 2088 14.08                1
    ## 2089 14.08                1
    ## 2090 14.08                1
    ## 2091 14.08                0
    ## 2092 14.08                0
    ## 2093 14.08                0
    ## 2094 14.08                0
    ## 2095 14.08                0
    ## 2096 14.08                0
    ## 2097 14.08                0
    ## 2098 14.08                0
    ## 2099 14.08                0
    ## 2100 14.08                0
    ## 2101 14.08                0
    ## 2102 14.08                0
    ## 2103 14.08                0
    ## 2104 14.08                0
    ## 2105 14.08                0
    ## 2106 14.08                0
    ## 2107 14.08                0
    ## 2108 14.08                0
    ## 2109 14.08                0
    ## 2110 14.33                1
    ## 2111 14.33                1
    ## 2112 14.33                1
    ## 2113 14.33                1
    ## 2114 14.33                1
    ## 2115 14.33                1
    ## 2116 14.33                1
    ## 2117 14.33                1
    ## 2118 14.33                1
    ## 2119 14.33                1
    ## 2120 14.33                1
    ## 2121 14.33                1
    ## 2122 14.33                1
    ## 2123 14.33                1
    ## 2124 14.33                1
    ## 2125 14.33                1
    ## 2126 14.33                1
    ## 2127 14.33                1
    ## 2128 14.33                1
    ## 2129 14.33                1
    ## 2130 14.33                1
    ## 2131 14.33                1
    ## 2132 14.33                1
    ## 2133 14.33                1
    ## 2134 14.33                1
    ## 2135 14.33                1
    ## 2136 14.33                1
    ## 2137 14.33                1
    ## 2138 14.33                1
    ## 2139 14.33                1
    ## 2140 14.33                1
    ## 2141 14.33                1
    ## 2142 14.33                1
    ## 2143 14.33                1
    ## 2144 14.33                1
    ## 2145 14.33                1
    ## 2146 14.33                1
    ## 2147 14.33                1
    ## 2148 14.33                1
    ## 2149 14.33                1
    ## 2150 14.33                1
    ## 2151 14.33                1
    ## 2152 14.33                1
    ## 2153 14.33                1
    ## 2154 14.33                1
    ## 2155 14.33                1
    ## 2156 14.33                1
    ## 2157 14.33                1
    ## 2158 14.33                1
    ## 2159 14.33                1
    ## 2160 14.33                1
    ## 2161 14.33                1
    ## 2162 14.33                1
    ## 2163 14.33                1
    ## 2164 14.33                1
    ## 2165 14.33                1
    ## 2166 14.33                1
    ## 2167 14.33                1
    ## 2168 14.33                1
    ## 2169 14.33                1
    ## 2170 14.33                1
    ## 2171 14.33                1
    ## 2172 14.33                1
    ## 2173 14.33                1
    ## 2174 14.33                1
    ## 2175 14.33                1
    ## 2176 14.33                1
    ## 2177 14.33                1
    ## 2178 14.33                1
    ## 2179 14.33                1
    ## 2180 14.33                1
    ## 2181 14.33                1
    ## 2182 14.33                1
    ## 2183 14.33                1
    ## 2184 14.33                1
    ## 2185 14.33                1
    ## 2186 14.33                1
    ## 2187 14.33                1
    ## 2188 14.33                1
    ## 2189 14.33                1
    ## 2190 14.33                1
    ## 2191 14.33                1
    ## 2192 14.33                1
    ## 2193 14.33                1
    ## 2194 14.33                1
    ## 2195 14.33                1
    ## 2196 14.33                1
    ## 2197 14.33                1
    ## 2198 14.33                1
    ## 2199 14.33                1
    ## 2200 14.33                0
    ## 2201 14.33                0
    ## 2202 14.33                0
    ## 2203 14.33                0
    ## 2204 14.33                0
    ## 2205 14.33                0
    ## 2206 14.33                0
    ## 2207 14.58                1
    ## 2208 14.58                1
    ## 2209 14.58                1
    ## 2210 14.58                1
    ## 2211 14.58                1
    ## 2212 14.58                1
    ## 2213 14.58                1
    ## 2214 14.58                1
    ## 2215 14.58                1
    ## 2216 14.58                1
    ## 2217 14.58                1
    ## 2218 14.58                1
    ## 2219 14.58                1
    ## 2220 14.58                1
    ## 2221 14.58                1
    ## 2222 14.58                1
    ## 2223 14.58                1
    ## 2224 14.58                1
    ## 2225 14.58                1
    ## 2226 14.58                1
    ## 2227 14.58                1
    ## 2228 14.58                1
    ## 2229 14.58                1
    ## 2230 14.58                1
    ## 2231 14.58                1
    ## 2232 14.58                1
    ## 2233 14.58                1
    ## 2234 14.58                1
    ## 2235 14.58                1
    ## 2236 14.58                1
    ## 2237 14.58                1
    ## 2238 14.58                1
    ## 2239 14.58                1
    ## 2240 14.58                1
    ## 2241 14.58                1
    ## 2242 14.58                1
    ## 2243 14.58                1
    ## 2244 14.58                1
    ## 2245 14.58                1
    ## 2246 14.58                1
    ## 2247 14.58                1
    ## 2248 14.58                1
    ## 2249 14.58                1
    ## 2250 14.58                1
    ## 2251 14.58                1
    ## 2252 14.58                1
    ## 2253 14.58                1
    ## 2254 14.58                1
    ## 2255 14.58                1
    ## 2256 14.58                1
    ## 2257 14.58                1
    ## 2258 14.58                1
    ## 2259 14.58                1
    ## 2260 14.58                1
    ## 2261 14.58                1
    ## 2262 14.58                1
    ## 2263 14.58                1
    ## 2264 14.58                1
    ## 2265 14.58                1
    ## 2266 14.58                1
    ## 2267 14.58                1
    ## 2268 14.58                1
    ## 2269 14.58                1
    ## 2270 14.58                1
    ## 2271 14.58                1
    ## 2272 14.58                1
    ## 2273 14.58                1
    ## 2274 14.58                1
    ## 2275 14.58                1
    ## 2276 14.58                1
    ## 2277 14.58                1
    ## 2278 14.58                1
    ## 2279 14.58                1
    ## 2280 14.58                1
    ## 2281 14.58                1
    ## 2282 14.58                1
    ## 2283 14.58                1
    ## 2284 14.58                1
    ## 2285 14.58                1
    ## 2286 14.58                1
    ## 2287 14.58                1
    ## 2288 14.58                1
    ## 2289 14.58                1
    ## 2290 14.58                1
    ## 2291 14.58                1
    ## 2292 14.58                1
    ## 2293 14.58                1
    ## 2294 14.58                1
    ## 2295 14.58                1
    ## 2296 14.58                1
    ## 2297 14.58                1
    ## 2298 14.58                1
    ## 2299 14.58                1
    ## 2300 14.58                1
    ## 2301 14.58                1
    ## 2302 14.58                1
    ## 2303 14.58                1
    ## 2304 14.58                1
    ## 2305 14.58                1
    ## 2306 14.58                1
    ## 2307 14.58                1
    ## 2308 14.58                1
    ## 2309 14.58                1
    ## 2310 14.58                1
    ## 2311 14.58                1
    ## 2312 14.58                1
    ## 2313 14.58                1
    ## 2314 14.58                1
    ## 2315 14.58                1
    ## 2316 14.58                1
    ## 2317 14.58                1
    ## 2318 14.58                1
    ## 2319 14.58                1
    ## 2320 14.58                0
    ## 2321 14.58                0
    ## 2322 14.58                0
    ## 2323 14.58                0
    ## 2324 14.58                0
    ## 2325 14.58                0
    ## 2326 14.58                0
    ## 2327 14.83                1
    ## 2328 14.83                1
    ## 2329 14.83                1
    ## 2330 14.83                1
    ## 2331 14.83                1
    ## 2332 14.83                1
    ## 2333 14.83                1
    ## 2334 14.83                1
    ## 2335 14.83                1
    ## 2336 14.83                1
    ## 2337 14.83                1
    ## 2338 14.83                1
    ## 2339 14.83                1
    ## 2340 14.83                1
    ## 2341 14.83                1
    ## 2342 14.83                1
    ## 2343 14.83                1
    ## 2344 14.83                1
    ## 2345 14.83                1
    ## 2346 14.83                1
    ## 2347 14.83                1
    ## 2348 14.83                1
    ## 2349 14.83                1
    ## 2350 14.83                1
    ## 2351 14.83                1
    ## 2352 14.83                1
    ## 2353 14.83                1
    ## 2354 14.83                1
    ## 2355 14.83                1
    ## 2356 14.83                1
    ## 2357 14.83                1
    ## 2358 14.83                1
    ## 2359 14.83                1
    ## 2360 14.83                1
    ## 2361 14.83                1
    ## 2362 14.83                1
    ## 2363 14.83                1
    ## 2364 14.83                1
    ## 2365 14.83                1
    ## 2366 14.83                1
    ## 2367 14.83                1
    ## 2368 14.83                1
    ## 2369 14.83                1
    ## 2370 14.83                1
    ## 2371 14.83                1
    ## 2372 14.83                1
    ## 2373 14.83                1
    ## 2374 14.83                1
    ## 2375 14.83                1
    ## 2376 14.83                1
    ## 2377 14.83                1
    ## 2378 14.83                1
    ## 2379 14.83                1
    ## 2380 14.83                1
    ## 2381 14.83                1
    ## 2382 14.83                1
    ## 2383 14.83                1
    ## 2384 14.83                1
    ## 2385 14.83                1
    ## 2386 14.83                1
    ## 2387 14.83                1
    ## 2388 14.83                1
    ## 2389 14.83                1
    ## 2390 14.83                1
    ## 2391 14.83                1
    ## 2392 14.83                1
    ## 2393 14.83                1
    ## 2394 14.83                1
    ## 2395 14.83                1
    ## 2396 14.83                1
    ## 2397 14.83                1
    ## 2398 14.83                1
    ## 2399 14.83                1
    ## 2400 14.83                1
    ## 2401 14.83                1
    ## 2402 14.83                1
    ## 2403 14.83                1
    ## 2404 14.83                1
    ## 2405 14.83                1
    ## 2406 14.83                1
    ## 2407 14.83                1
    ## 2408 14.83                1
    ## 2409 14.83                1
    ## 2410 14.83                1
    ## 2411 14.83                1
    ## 2412 14.83                1
    ## 2413 14.83                1
    ## 2414 14.83                1
    ## 2415 14.83                1
    ## 2416 14.83                1
    ## 2417 14.83                1
    ## 2418 14.83                1
    ## 2419 14.83                1
    ## 2420 14.83                1
    ## 2421 14.83                1
    ## 2422 14.83                0
    ## 2423 14.83                0
    ## 2424 14.83                0
    ## 2425 14.83                0
    ## 2426 14.83                0
    ## 2427 14.83                0
    ## 2428 14.83                0
    ## 2429 15.08                1
    ## 2430 15.08                1
    ## 2431 15.08                1
    ## 2432 15.08                1
    ## 2433 15.08                1
    ## 2434 15.08                1
    ## 2435 15.08                1
    ## 2436 15.08                1
    ## 2437 15.08                1
    ## 2438 15.08                1
    ## 2439 15.08                1
    ## 2440 15.08                1
    ## 2441 15.08                1
    ## 2442 15.08                1
    ## 2443 15.08                1
    ## 2444 15.08                1
    ## 2445 15.08                1
    ## 2446 15.08                1
    ## 2447 15.08                1
    ## 2448 15.08                1
    ## 2449 15.08                1
    ## 2450 15.08                1
    ## 2451 15.08                1
    ## 2452 15.08                1
    ## 2453 15.08                1
    ## 2454 15.08                1
    ## 2455 15.08                1
    ## 2456 15.08                1
    ## 2457 15.08                1
    ## 2458 15.08                1
    ## 2459 15.08                1
    ## 2460 15.08                1
    ## 2461 15.08                1
    ## 2462 15.08                1
    ## 2463 15.08                1
    ## 2464 15.08                1
    ## 2465 15.08                1
    ## 2466 15.08                1
    ## 2467 15.08                1
    ## 2468 15.08                1
    ## 2469 15.08                1
    ## 2470 15.08                1
    ## 2471 15.08                1
    ## 2472 15.08                1
    ## 2473 15.08                1
    ## 2474 15.08                1
    ## 2475 15.08                1
    ## 2476 15.08                1
    ## 2477 15.08                1
    ## 2478 15.08                1
    ## 2479 15.08                1
    ## 2480 15.08                1
    ## 2481 15.08                1
    ## 2482 15.08                1
    ## 2483 15.08                1
    ## 2484 15.08                1
    ## 2485 15.08                1
    ## 2486 15.08                1
    ## 2487 15.08                1
    ## 2488 15.08                1
    ## 2489 15.08                1
    ## 2490 15.08                1
    ## 2491 15.08                1
    ## 2492 15.08                1
    ## 2493 15.08                1
    ## 2494 15.08                1
    ## 2495 15.08                1
    ## 2496 15.08                1
    ## 2497 15.08                1
    ## 2498 15.08                1
    ## 2499 15.08                1
    ## 2500 15.08                1
    ## 2501 15.08                1
    ## 2502 15.08                1
    ## 2503 15.08                1
    ## 2504 15.08                1
    ## 2505 15.08                1
    ## 2506 15.08                1
    ## 2507 15.08                1
    ## 2508 15.08                1
    ## 2509 15.08                1
    ## 2510 15.08                1
    ## 2511 15.08                1
    ## 2512 15.08                1
    ## 2513 15.08                1
    ## 2514 15.08                1
    ## 2515 15.08                1
    ## 2516 15.08                1
    ## 2517 15.08                1
    ## 2518 15.08                1
    ## 2519 15.08                1
    ## 2520 15.08                1
    ## 2521 15.08                1
    ## 2522 15.08                1
    ## 2523 15.08                1
    ## 2524 15.08                1
    ## 2525 15.08                1
    ## 2526 15.08                1
    ## 2527 15.08                1
    ## 2528 15.08                1
    ## 2529 15.08                1
    ## 2530 15.08                1
    ## 2531 15.08                1
    ## 2532 15.08                1
    ## 2533 15.08                1
    ## 2534 15.08                1
    ## 2535 15.08                1
    ## 2536 15.08                1
    ## 2537 15.08                1
    ## 2538 15.08                1
    ## 2539 15.08                1
    ## 2540 15.08                1
    ## 2541 15.08                1
    ## 2542 15.08                1
    ## 2543 15.08                1
    ## 2544 15.08                1
    ## 2545 15.08                1
    ## 2546 15.08                0
    ## 2547 15.08                0
    ## 2548 15.08                0
    ## 2549 15.08                0
    ## 2550 15.08                0
    ## 2551 15.33                1
    ## 2552 15.33                1
    ## 2553 15.33                1
    ## 2554 15.33                1
    ## 2555 15.33                1
    ## 2556 15.33                1
    ## 2557 15.33                1
    ## 2558 15.33                1
    ## 2559 15.33                1
    ## 2560 15.33                1
    ## 2561 15.33                1
    ## 2562 15.33                1
    ## 2563 15.33                1
    ## 2564 15.33                1
    ## 2565 15.33                1
    ## 2566 15.33                1
    ## 2567 15.33                1
    ## 2568 15.33                1
    ## 2569 15.33                1
    ## 2570 15.33                1
    ## 2571 15.33                1
    ## 2572 15.33                1
    ## 2573 15.33                1
    ## 2574 15.33                1
    ## 2575 15.33                1
    ## 2576 15.33                1
    ## 2577 15.33                1
    ## 2578 15.33                1
    ## 2579 15.33                1
    ## 2580 15.33                1
    ## 2581 15.33                1
    ## 2582 15.33                1
    ## 2583 15.33                1
    ## 2584 15.33                1
    ## 2585 15.33                1
    ## 2586 15.33                1
    ## 2587 15.33                1
    ## 2588 15.33                1
    ## 2589 15.33                1
    ## 2590 15.33                1
    ## 2591 15.33                1
    ## 2592 15.33                1
    ## 2593 15.33                1
    ## 2594 15.33                1
    ## 2595 15.33                1
    ## 2596 15.33                1
    ## 2597 15.33                1
    ## 2598 15.33                1
    ## 2599 15.33                1
    ## 2600 15.33                1
    ## 2601 15.33                1
    ## 2602 15.33                1
    ## 2603 15.33                1
    ## 2604 15.33                1
    ## 2605 15.33                1
    ## 2606 15.33                1
    ## 2607 15.33                1
    ## 2608 15.33                1
    ## 2609 15.33                1
    ## 2610 15.33                1
    ## 2611 15.33                1
    ## 2612 15.33                1
    ## 2613 15.33                1
    ## 2614 15.33                1
    ## 2615 15.33                1
    ## 2616 15.33                1
    ## 2617 15.33                1
    ## 2618 15.33                1
    ## 2619 15.33                1
    ## 2620 15.33                1
    ## 2621 15.33                1
    ## 2622 15.33                1
    ## 2623 15.33                1
    ## 2624 15.33                1
    ## 2625 15.33                1
    ## 2626 15.33                1
    ## 2627 15.33                1
    ## 2628 15.33                1
    ## 2629 15.33                1
    ## 2630 15.33                1
    ## 2631 15.33                1
    ## 2632 15.33                1
    ## 2633 15.33                1
    ## 2634 15.33                1
    ## 2635 15.33                1
    ## 2636 15.33                1
    ## 2637 15.33                1
    ## 2638 15.33                1
    ## 2639 15.33                1
    ## 2640 15.33                1
    ## 2641 15.33                1
    ## 2642 15.33                1
    ## 2643 15.33                1
    ## 2644 15.33                1
    ## 2645 15.33                1
    ## 2646 15.33                1
    ## 2647 15.33                1
    ## 2648 15.33                1
    ## 2649 15.33                1
    ## 2650 15.33                1
    ## 2651 15.33                1
    ## 2652 15.33                1
    ## 2653 15.33                1
    ## 2654 15.33                1
    ## 2655 15.33                1
    ## 2656 15.33                1
    ## 2657 15.33                1
    ## 2658 15.33                0
    ## 2659 15.33                0
    ## 2660 15.33                0
    ## 2661 15.33                0
    ## 2662 15.58                1
    ## 2663 15.58                1
    ## 2664 15.58                1
    ## 2665 15.58                1
    ## 2666 15.58                1
    ## 2667 15.58                1
    ## 2668 15.58                1
    ## 2669 15.58                1
    ## 2670 15.58                1
    ## 2671 15.58                1
    ## 2672 15.58                1
    ## 2673 15.58                1
    ## 2674 15.58                1
    ## 2675 15.58                1
    ## 2676 15.58                1
    ## 2677 15.58                1
    ## 2678 15.58                1
    ## 2679 15.58                1
    ## 2680 15.58                1
    ## 2681 15.58                1
    ## 2682 15.58                1
    ## 2683 15.58                1
    ## 2684 15.58                1
    ## 2685 15.58                1
    ## 2686 15.58                1
    ## 2687 15.58                1
    ## 2688 15.58                1
    ## 2689 15.58                1
    ## 2690 15.58                1
    ## 2691 15.58                1
    ## 2692 15.58                1
    ## 2693 15.58                1
    ## 2694 15.58                1
    ## 2695 15.58                1
    ## 2696 15.58                1
    ## 2697 15.58                1
    ## 2698 15.58                1
    ## 2699 15.58                1
    ## 2700 15.58                1
    ## 2701 15.58                1
    ## 2702 15.58                1
    ## 2703 15.58                1
    ## 2704 15.58                1
    ## 2705 15.58                1
    ## 2706 15.58                1
    ## 2707 15.58                1
    ## 2708 15.58                1
    ## 2709 15.58                1
    ## 2710 15.58                1
    ## 2711 15.58                1
    ## 2712 15.58                1
    ## 2713 15.58                1
    ## 2714 15.58                1
    ## 2715 15.58                1
    ## 2716 15.58                1
    ## 2717 15.58                1
    ## 2718 15.58                1
    ## 2719 15.58                1
    ## 2720 15.58                1
    ## 2721 15.58                1
    ## 2722 15.58                1
    ## 2723 15.58                1
    ## 2724 15.58                1
    ## 2725 15.58                1
    ## 2726 15.58                1
    ## 2727 15.58                1
    ## 2728 15.58                1
    ## 2729 15.58                1
    ## 2730 15.58                1
    ## 2731 15.58                1
    ## 2732 15.58                1
    ## 2733 15.58                1
    ## 2734 15.58                1
    ## 2735 15.58                1
    ## 2736 15.58                1
    ## 2737 15.58                1
    ## 2738 15.58                1
    ## 2739 15.58                1
    ## 2740 15.58                1
    ## 2741 15.58                1
    ## 2742 15.58                1
    ## 2743 15.58                1
    ## 2744 15.58                1
    ## 2745 15.58                1
    ## 2746 15.58                1
    ## 2747 15.58                1
    ## 2748 15.58                1
    ## 2749 15.58                1
    ## 2750 15.58                1
    ## 2751 15.58                1
    ## 2752 15.58                1
    ## 2753 15.58                1
    ## 2754 15.58                0
    ## 2755 15.58                0
    ## 2756 15.83                1
    ## 2757 15.83                1
    ## 2758 15.83                1
    ## 2759 15.83                1
    ## 2760 15.83                1
    ## 2761 15.83                1
    ## 2762 15.83                1
    ## 2763 15.83                1
    ## 2764 15.83                1
    ## 2765 15.83                1
    ## 2766 15.83                1
    ## 2767 15.83                1
    ## 2768 15.83                1
    ## 2769 15.83                1
    ## 2770 15.83                1
    ## 2771 15.83                1
    ## 2772 15.83                1
    ## 2773 15.83                1
    ## 2774 15.83                1
    ## 2775 15.83                1
    ## 2776 15.83                1
    ## 2777 15.83                1
    ## 2778 15.83                1
    ## 2779 15.83                1
    ## 2780 15.83                1
    ## 2781 15.83                1
    ## 2782 15.83                1
    ## 2783 15.83                1
    ## 2784 15.83                1
    ## 2785 15.83                1
    ## 2786 15.83                1
    ## 2787 15.83                1
    ## 2788 15.83                1
    ## 2789 15.83                1
    ## 2790 15.83                1
    ## 2791 15.83                1
    ## 2792 15.83                1
    ## 2793 15.83                1
    ## 2794 15.83                1
    ## 2795 15.83                1
    ## 2796 15.83                1
    ## 2797 15.83                1
    ## 2798 15.83                1
    ## 2799 15.83                1
    ## 2800 15.83                1
    ## 2801 15.83                1
    ## 2802 15.83                1
    ## 2803 15.83                1
    ## 2804 15.83                1
    ## 2805 15.83                1
    ## 2806 15.83                1
    ## 2807 15.83                1
    ## 2808 15.83                1
    ## 2809 15.83                1
    ## 2810 15.83                1
    ## 2811 15.83                1
    ## 2812 15.83                1
    ## 2813 15.83                1
    ## 2814 15.83                1
    ## 2815 15.83                1
    ## 2816 15.83                1
    ## 2817 15.83                1
    ## 2818 15.83                1
    ## 2819 15.83                1
    ## 2820 15.83                1
    ## 2821 15.83                1
    ## 2822 15.83                1
    ## 2823 15.83                1
    ## 2824 15.83                1
    ## 2825 15.83                1
    ## 2826 15.83                1
    ## 2827 15.83                1
    ## 2828 15.83                1
    ## 2829 15.83                1
    ## 2830 15.83                1
    ## 2831 15.83                1
    ## 2832 15.83                1
    ## 2833 15.83                1
    ## 2834 15.83                1
    ## 2835 15.83                1
    ## 2836 15.83                1
    ## 2837 15.83                1
    ## 2838 15.83                1
    ## 2839 15.83                1
    ## 2840 15.83                1
    ## 2841 15.83                1
    ## 2842 15.83                1
    ## 2843 15.83                1
    ## 2844 15.83                1
    ## 2845 15.83                1
    ## 2846 15.83                1
    ## 2847 15.83                1
    ## 2848 15.83                1
    ## 2849 15.83                1
    ## 2850 15.83                1
    ## 2851 15.83                1
    ## 2852 15.83                1
    ## 2853 15.83                1
    ## 2854 15.83                1
    ## 2855 15.83                1
    ## 2856 15.83                1
    ## 2857 15.83                1
    ## 2858 15.83                1
    ## 2859 15.83                1
    ## 2860 15.83                1
    ## 2861 15.83                1
    ## 2862 15.83                1
    ## 2863 15.83                1
    ## 2864 15.83                1
    ## 2865 15.83                1
    ## 2866 15.83                1
    ## 2867 15.83                1
    ## 2868 15.83                0
    ## 2869 15.83                0
    ## 2870 17.58                1
    ## 2871 17.58                1
    ## 2872 17.58                1
    ## 2873 17.58                1
    ## 2874 17.58                1
    ## 2875 17.58                1
    ## 2876 17.58                1
    ## 2877 17.58                1
    ## 2878 17.58                1
    ## 2879 17.58                1
    ## 2880 17.58                1
    ## 2881 17.58                1
    ## 2882 17.58                1
    ## 2883 17.58                1
    ## 2884 17.58                1
    ## 2885 17.58                1
    ## 2886 17.58                1
    ## 2887 17.58                1
    ## 2888 17.58                1
    ## 2889 17.58                1
    ## 2890 17.58                1
    ## 2891 17.58                1
    ## 2892 17.58                1
    ## 2893 17.58                1
    ## 2894 17.58                1
    ## 2895 17.58                1
    ## 2896 17.58                1
    ## 2897 17.58                1
    ## 2898 17.58                1
    ## 2899 17.58                1
    ## 2900 17.58                1
    ## 2901 17.58                1
    ## 2902 17.58                1
    ## 2903 17.58                1
    ## 2904 17.58                1
    ## 2905 17.58                1
    ## 2906 17.58                1
    ## 2907 17.58                1
    ## 2908 17.58                1
    ## 2909 17.58                1
    ## 2910 17.58                1
    ## 2911 17.58                1
    ## 2912 17.58                1
    ## 2913 17.58                1
    ## 2914 17.58                1
    ## 2915 17.58                1
    ## 2916 17.58                1
    ## 2917 17.58                1
    ## 2918 17.58                1
    ## 2919 17.58                1
    ## 2920 17.58                1
    ## 2921 17.58                1
    ## 2922 17.58                1
    ## 2923 17.58                1
    ## 2924 17.58                1
    ## 2925 17.58                1
    ## 2926 17.58                1
    ## 2927 17.58                1
    ## 2928 17.58                1
    ## 2929 17.58                1
    ## 2930 17.58                1
    ## 2931 17.58                1
    ## 2932 17.58                1
    ## 2933 17.58                1
    ## 2934 17.58                1
    ## 2935 17.58                1
    ## 2936 17.58                1
    ## 2937 17.58                1
    ## 2938 17.58                1
    ## 2939 17.58                1
    ## 2940 17.58                1
    ## 2941 17.58                1
    ## 2942 17.58                1
    ## 2943 17.58                1
    ## 2944 17.58                1
    ## 2945 17.58                1
    ## 2946 17.58                1
    ## 2947 17.58                1
    ## 2948 17.58                1
    ## 2949 17.58                1
    ## 2950 17.58                1
    ## 2951 17.58                1
    ## 2952 17.58                1
    ## 2953 17.58                1
    ## 2954 17.58                1
    ## 2955 17.58                1
    ## 2956 17.58                1
    ## 2957 17.58                1
    ## 2958 17.58                1
    ## 2959 17.58                1
    ## 2960 17.58                1
    ## 2961 17.58                1
    ## 2962 17.58                1
    ## 2963 17.58                1
    ## 2964 17.58                1
    ## 2965 17.58                1
    ## 2966 17.58                1
    ## 2967 17.58                1
    ## 2968 17.58                1
    ## 2969 17.58                1
    ## 2970 17.58                1
    ## 2971 17.58                1
    ## 2972 17.58                1
    ## 2973 17.58                1
    ## 2974 17.58                1
    ## 2975 17.58                1
    ## 2976 17.58                1
    ## 2977 17.58                1
    ## 2978 17.58                1
    ## 2979 17.58                1
    ## 2980 17.58                1
    ## 2981 17.58                1
    ## 2982 17.58                1
    ## 2983 17.58                1
    ## 2984 17.58                1
    ## 2985 17.58                1
    ## 2986 17.58                1
    ## 2987 17.58                1
    ## 2988 17.58                1
    ## 2989 17.58                1
    ## 2990 17.58                1
    ## 2991 17.58                1
    ## 2992 17.58                1
    ## 2993 17.58                1
    ## 2994 17.58                1
    ## 2995 17.58                1
    ## 2996 17.58                1
    ## 2997 17.58                1
    ## 2998 17.58                1
    ## 2999 17.58                1
    ## 3000 17.58                1
    ## 3001 17.58                1
    ## 3002 17.58                1
    ## 3003 17.58                1
    ## 3004 17.58                1
    ## 3005 17.58                1
    ## 3006 17.58                1
    ## 3007 17.58                1
    ## 3008 17.58                1
    ## 3009 17.58                1
    ## 3010 17.58                1
    ## 3011 17.58                1
    ## 3012 17.58                1
    ## 3013 17.58                1
    ## 3014 17.58                1
    ## 3015 17.58                1
    ## 3016 17.58                1
    ## 3017 17.58                1
    ## 3018 17.58                1
    ## 3019 17.58                1
    ## 3020 17.58                1
    ## 3021 17.58                1
    ## 3022 17.58                1
    ## 3023 17.58                1
    ## 3024 17.58                1
    ## 3025 17.58                1
    ## 3026 17.58                1
    ## 3027 17.58                1
    ## 3028 17.58                1
    ## 3029 17.58                1
    ## 3030 17.58                1
    ## 3031 17.58                1
    ## 3032 17.58                1
    ## 3033 17.58                1
    ## 3034 17.58                1
    ## 3035 17.58                1
    ## 3036 17.58                1
    ## 3037 17.58                1
    ## 3038 17.58                1
    ## 3039 17.58                1
    ## 3040 17.58                1
    ## 3041 17.58                1
    ## 3042 17.58                1
    ## 3043 17.58                1
    ## 3044 17.58                1
    ## 3045 17.58                1
    ## 3046 17.58                1
    ## 3047 17.58                1
    ## 3048 17.58                1
    ## 3049 17.58                1
    ## 3050 17.58                1
    ## 3051 17.58                1
    ## 3052 17.58                1
    ## 3053 17.58                1
    ## 3054 17.58                1
    ## 3055 17.58                1
    ## 3056 17.58                1
    ## 3057 17.58                1
    ## 3058 17.58                1
    ## 3059 17.58                1
    ## 3060 17.58                1
    ## 3061 17.58                1
    ## 3062 17.58                1
    ## 3063 17.58                1
    ## 3064 17.58                1
    ## 3065 17.58                1
    ## 3066 17.58                1
    ## 3067 17.58                1
    ## 3068 17.58                1
    ## 3069 17.58                1
    ## 3070 17.58                1
    ## 3071 17.58                1
    ## 3072 17.58                1
    ## 3073 17.58                1
    ## 3074 17.58                1
    ## 3075 17.58                1
    ## 3076 17.58                1
    ## 3077 17.58                1
    ## 3078 17.58                1
    ## 3079 17.58                1
    ## 3080 17.58                1
    ## 3081 17.58                1
    ## 3082 17.58                1
    ## 3083 17.58                1
    ## 3084 17.58                1
    ## 3085 17.58                1
    ## 3086 17.58                1
    ## 3087 17.58                1
    ## 3088 17.58                1
    ## 3089 17.58                1
    ## 3090 17.58                1
    ## 3091 17.58                1
    ## 3092 17.58                1
    ## 3093 17.58                1
    ## 3094 17.58                1
    ## 3095 17.58                1
    ## 3096 17.58                1
    ## 3097 17.58                1
    ## 3098 17.58                1
    ## 3099 17.58                1
    ## 3100 17.58                1
    ## 3101 17.58                1
    ## 3102 17.58                1
    ## 3103 17.58                1
    ## 3104 17.58                1
    ## 3105 17.58                1
    ## 3106 17.58                1
    ## 3107 17.58                1
    ## 3108 17.58                1
    ## 3109 17.58                1
    ## 3110 17.58                1
    ## 3111 17.58                1
    ## 3112 17.58                1
    ## 3113 17.58                1
    ## 3114 17.58                1
    ## 3115 17.58                1
    ## 3116 17.58                1
    ## 3117 17.58                1
    ## 3118 17.58                1
    ## 3119 17.58                1
    ## 3120 17.58                1
    ## 3121 17.58                1
    ## 3122 17.58                1
    ## 3123 17.58                1
    ## 3124 17.58                1
    ## 3125 17.58                1
    ## 3126 17.58                1
    ## 3127 17.58                1
    ## 3128 17.58                1
    ## 3129 17.58                1
    ## 3130 17.58                1
    ## 3131 17.58                1
    ## 3132 17.58                1
    ## 3133 17.58                1
    ## 3134 17.58                1
    ## 3135 17.58                1
    ## 3136 17.58                1
    ## 3137 17.58                1
    ## 3138 17.58                1
    ## 3139 17.58                1
    ## 3140 17.58                1
    ## 3141 17.58                1
    ## 3142 17.58                1
    ## 3143 17.58                1
    ## 3144 17.58                1
    ## 3145 17.58                1
    ## 3146 17.58                1
    ## 3147 17.58                1
    ## 3148 17.58                1
    ## 3149 17.58                1
    ## 3150 17.58                1
    ## 3151 17.58                1
    ## 3152 17.58                1
    ## 3153 17.58                1
    ## 3154 17.58                1
    ## 3155 17.58                1
    ## 3156 17.58                1
    ## 3157 17.58                1
    ## 3158 17.58                1
    ## 3159 17.58                1
    ## 3160 17.58                1
    ## 3161 17.58                1
    ## 3162 17.58                1
    ## 3163 17.58                1
    ## 3164 17.58                1
    ## 3165 17.58                1
    ## 3166 17.58                1
    ## 3167 17.58                1
    ## 3168 17.58                1
    ## 3169 17.58                1
    ## 3170 17.58                1
    ## 3171 17.58                1
    ## 3172 17.58                1
    ## 3173 17.58                1
    ## 3174 17.58                1
    ## 3175 17.58                1
    ## 3176 17.58                1
    ## 3177 17.58                1
    ## 3178 17.58                1
    ## 3179 17.58                1
    ## 3180 17.58                1
    ## 3181 17.58                1
    ## 3182 17.58                1
    ## 3183 17.58                1
    ## 3184 17.58                1
    ## 3185 17.58                1
    ## 3186 17.58                1
    ## 3187 17.58                1
    ## 3188 17.58                1
    ## 3189 17.58                1
    ## 3190 17.58                1
    ## 3191 17.58                1
    ## 3192 17.58                1
    ## 3193 17.58                1
    ## 3194 17.58                1
    ## 3195 17.58                1
    ## 3196 17.58                1
    ## 3197 17.58                1
    ## 3198 17.58                1
    ## 3199 17.58                1
    ## 3200 17.58                1
    ## 3201 17.58                1
    ## 3202 17.58                1
    ## 3203 17.58                1
    ## 3204 17.58                1
    ## 3205 17.58                1
    ## 3206 17.58                1
    ## 3207 17.58                1
    ## 3208 17.58                1
    ## 3209 17.58                1
    ## 3210 17.58                1
    ## 3211 17.58                1
    ## 3212 17.58                1
    ## 3213 17.58                1
    ## 3214 17.58                1
    ## 3215 17.58                1
    ## 3216 17.58                1
    ## 3217 17.58                1
    ## 3218 17.58                1
    ## 3219 17.58                1
    ## 3220 17.58                1
    ## 3221 17.58                1
    ## 3222 17.58                1
    ## 3223 17.58                1
    ## 3224 17.58                1
    ## 3225 17.58                1
    ## 3226 17.58                1
    ## 3227 17.58                1
    ## 3228 17.58                1
    ## 3229 17.58                1
    ## 3230 17.58                1
    ## 3231 17.58                1
    ## 3232 17.58                1
    ## 3233 17.58                1
    ## 3234 17.58                1
    ## 3235 17.58                1
    ## 3236 17.58                1
    ## 3237 17.58                1
    ## 3238 17.58                1
    ## 3239 17.58                1
    ## 3240 17.58                1
    ## 3241 17.58                1
    ## 3242 17.58                1
    ## 3243 17.58                1
    ## 3244 17.58                1
    ## 3245 17.58                1
    ## 3246 17.58                1
    ## 3247 17.58                1
    ## 3248 17.58                1
    ## 3249 17.58                1
    ## 3250 17.58                1
    ## 3251 17.58                1
    ## 3252 17.58                1
    ## 3253 17.58                1
    ## 3254 17.58                1
    ## 3255 17.58                1
    ## 3256 17.58                1
    ## 3257 17.58                1
    ## 3258 17.58                1
    ## 3259 17.58                1
    ## 3260 17.58                1
    ## 3261 17.58                1
    ## 3262 17.58                1
    ## 3263 17.58                1
    ## 3264 17.58                1
    ## 3265 17.58                1
    ## 3266 17.58                1
    ## 3267 17.58                1
    ## 3268 17.58                1
    ## 3269 17.58                1
    ## 3270 17.58                1
    ## 3271 17.58                1
    ## 3272 17.58                1
    ## 3273 17.58                1
    ## 3274 17.58                1
    ## 3275 17.58                1
    ## 3276 17.58                1
    ## 3277 17.58                1
    ## 3278 17.58                1
    ## 3279 17.58                1
    ## 3280 17.58                1
    ## 3281 17.58                1
    ## 3282 17.58                1
    ## 3283 17.58                1
    ## 3284 17.58                1
    ## 3285 17.58                1
    ## 3286 17.58                1
    ## 3287 17.58                1
    ## 3288 17.58                1
    ## 3289 17.58                1
    ## 3290 17.58                1
    ## 3291 17.58                1
    ## 3292 17.58                1
    ## 3293 17.58                1
    ## 3294 17.58                1
    ## 3295 17.58                1
    ## 3296 17.58                1
    ## 3297 17.58                1
    ## 3298 17.58                1
    ## 3299 17.58                1
    ## 3300 17.58                1
    ## 3301 17.58                1
    ## 3302 17.58                1
    ## 3303 17.58                1
    ## 3304 17.58                1
    ## 3305 17.58                1
    ## 3306 17.58                1
    ## 3307 17.58                1
    ## 3308 17.58                1
    ## 3309 17.58                1
    ## 3310 17.58                1
    ## 3311 17.58                1
    ## 3312 17.58                1
    ## 3313 17.58                1
    ## 3314 17.58                1
    ## 3315 17.58                1
    ## 3316 17.58                1
    ## 3317 17.58                1
    ## 3318 17.58                1
    ## 3319 17.58                1
    ## 3320 17.58                1
    ## 3321 17.58                1
    ## 3322 17.58                1
    ## 3323 17.58                1
    ## 3324 17.58                1
    ## 3325 17.58                1
    ## 3326 17.58                1
    ## 3327 17.58                1
    ## 3328 17.58                1
    ## 3329 17.58                1
    ## 3330 17.58                1
    ## 3331 17.58                1
    ## 3332 17.58                1
    ## 3333 17.58                1
    ## 3334 17.58                1
    ## 3335 17.58                1
    ## 3336 17.58                1
    ## 3337 17.58                1
    ## 3338 17.58                1
    ## 3339 17.58                1
    ## 3340 17.58                1
    ## 3341 17.58                1
    ## 3342 17.58                1
    ## 3343 17.58                1
    ## 3344 17.58                1
    ## 3345 17.58                1
    ## 3346 17.58                1
    ## 3347 17.58                1
    ## 3348 17.58                1
    ## 3349 17.58                1
    ## 3350 17.58                1
    ## 3351 17.58                1
    ## 3352 17.58                1
    ## 3353 17.58                1
    ## 3354 17.58                1
    ## 3355 17.58                1
    ## 3356 17.58                1
    ## 3357 17.58                1
    ## 3358 17.58                1
    ## 3359 17.58                1
    ## 3360 17.58                1
    ## 3361 17.58                1
    ## 3362 17.58                1
    ## 3363 17.58                1
    ## 3364 17.58                1
    ## 3365 17.58                1
    ## 3366 17.58                1
    ## 3367 17.58                1
    ## 3368 17.58                1
    ## 3369 17.58                1
    ## 3370 17.58                1
    ## 3371 17.58                1
    ## 3372 17.58                1
    ## 3373 17.58                1
    ## 3374 17.58                1
    ## 3375 17.58                1
    ## 3376 17.58                1
    ## 3377 17.58                1
    ## 3378 17.58                1
    ## 3379 17.58                1
    ## 3380 17.58                1
    ## 3381 17.58                1
    ## 3382 17.58                1
    ## 3383 17.58                1
    ## 3384 17.58                1
    ## 3385 17.58                1
    ## 3386 17.58                1
    ## 3387 17.58                1
    ## 3388 17.58                1
    ## 3389 17.58                1
    ## 3390 17.58                1
    ## 3391 17.58                1
    ## 3392 17.58                1
    ## 3393 17.58                1
    ## 3394 17.58                1
    ## 3395 17.58                1
    ## 3396 17.58                1
    ## 3397 17.58                1
    ## 3398 17.58                1
    ## 3399 17.58                1
    ## 3400 17.58                1
    ## 3401 17.58                1
    ## 3402 17.58                1
    ## 3403 17.58                1
    ## 3404 17.58                1
    ## 3405 17.58                1
    ## 3406 17.58                1
    ## 3407 17.58                1
    ## 3408 17.58                1
    ## 3409 17.58                1
    ## 3410 17.58                1
    ## 3411 17.58                1
    ## 3412 17.58                1
    ## 3413 17.58                1
    ## 3414 17.58                1
    ## 3415 17.58                1
    ## 3416 17.58                1
    ## 3417 17.58                1
    ## 3418 17.58                1
    ## 3419 17.58                1
    ## 3420 17.58                1
    ## 3421 17.58                1
    ## 3422 17.58                1
    ## 3423 17.58                1
    ## 3424 17.58                1
    ## 3425 17.58                1
    ## 3426 17.58                1
    ## 3427 17.58                1
    ## 3428 17.58                1
    ## 3429 17.58                1
    ## 3430 17.58                1
    ## 3431 17.58                1
    ## 3432 17.58                1
    ## 3433 17.58                1
    ## 3434 17.58                1
    ## 3435 17.58                1
    ## 3436 17.58                1
    ## 3437 17.58                1
    ## 3438 17.58                1
    ## 3439 17.58                1
    ## 3440 17.58                1
    ## 3441 17.58                1
    ## 3442 17.58                1
    ## 3443 17.58                1
    ## 3444 17.58                1
    ## 3445 17.58                1
    ## 3446 17.58                1
    ## 3447 17.58                1
    ## 3448 17.58                1
    ## 3449 17.58                1
    ## 3450 17.58                1
    ## 3451 17.58                1
    ## 3452 17.58                1
    ## 3453 17.58                1
    ## 3454 17.58                1
    ## 3455 17.58                1
    ## 3456 17.58                1
    ## 3457 17.58                1
    ## 3458 17.58                1
    ## 3459 17.58                1
    ## 3460 17.58                1
    ## 3461 17.58                1
    ## 3462 17.58                1
    ## 3463 17.58                1
    ## 3464 17.58                1
    ## 3465 17.58                1
    ## 3466 17.58                1
    ## 3467 17.58                1
    ## 3468 17.58                1
    ## 3469 17.58                1
    ## 3470 17.58                1
    ## 3471 17.58                1
    ## 3472 17.58                1
    ## 3473 17.58                1
    ## 3474 17.58                1
    ## 3475 17.58                1
    ## 3476 17.58                1
    ## 3477 17.58                1
    ## 3478 17.58                1
    ## 3479 17.58                1
    ## 3480 17.58                1
    ## 3481 17.58                1
    ## 3482 17.58                1
    ## 3483 17.58                1
    ## 3484 17.58                1
    ## 3485 17.58                1
    ## 3486 17.58                1
    ## 3487 17.58                1
    ## 3488 17.58                1
    ## 3489 17.58                1
    ## 3490 17.58                1
    ## 3491 17.58                1
    ## 3492 17.58                1
    ## 3493 17.58                1
    ## 3494 17.58                1
    ## 3495 17.58                1
    ## 3496 17.58                1
    ## 3497 17.58                1
    ## 3498 17.58                1
    ## 3499 17.58                1
    ## 3500 17.58                1
    ## 3501 17.58                1
    ## 3502 17.58                1
    ## 3503 17.58                1
    ## 3504 17.58                1
    ## 3505 17.58                1
    ## 3506 17.58                1
    ## 3507 17.58                1
    ## 3508 17.58                1
    ## 3509 17.58                1
    ## 3510 17.58                1
    ## 3511 17.58                1
    ## 3512 17.58                1
    ## 3513 17.58                1
    ## 3514 17.58                1
    ## 3515 17.58                1
    ## 3516 17.58                1
    ## 3517 17.58                1
    ## 3518 17.58                1
    ## 3519 17.58                1
    ## 3520 17.58                1
    ## 3521 17.58                1
    ## 3522 17.58                1
    ## 3523 17.58                1
    ## 3524 17.58                1
    ## 3525 17.58                1
    ## 3526 17.58                1
    ## 3527 17.58                1
    ## 3528 17.58                1
    ## 3529 17.58                1
    ## 3530 17.58                1
    ## 3531 17.58                1
    ## 3532 17.58                1
    ## 3533 17.58                1
    ## 3534 17.58                1
    ## 3535 17.58                1
    ## 3536 17.58                1
    ## 3537 17.58                1
    ## 3538 17.58                1
    ## 3539 17.58                1
    ## 3540 17.58                1
    ## 3541 17.58                1
    ## 3542 17.58                1
    ## 3543 17.58                1
    ## 3544 17.58                1
    ## 3545 17.58                1
    ## 3546 17.58                1
    ## 3547 17.58                1
    ## 3548 17.58                1
    ## 3549 17.58                1
    ## 3550 17.58                1
    ## 3551 17.58                1
    ## 3552 17.58                1
    ## 3553 17.58                1
    ## 3554 17.58                1
    ## 3555 17.58                1
    ## 3556 17.58                1
    ## 3557 17.58                1
    ## 3558 17.58                1
    ## 3559 17.58                1
    ## 3560 17.58                1
    ## 3561 17.58                1
    ## 3562 17.58                1
    ## 3563 17.58                1
    ## 3564 17.58                1
    ## 3565 17.58                1
    ## 3566 17.58                1
    ## 3567 17.58                1
    ## 3568 17.58                1
    ## 3569 17.58                1
    ## 3570 17.58                1
    ## 3571 17.58                1
    ## 3572 17.58                1
    ## 3573 17.58                1
    ## 3574 17.58                1
    ## 3575 17.58                1
    ## 3576 17.58                1
    ## 3577 17.58                1
    ## 3578 17.58                1
    ## 3579 17.58                1
    ## 3580 17.58                1
    ## 3581 17.58                1
    ## 3582 17.58                1
    ## 3583 17.58                1
    ## 3584 17.58                1
    ## 3585 17.58                1
    ## 3586 17.58                1
    ## 3587 17.58                1
    ## 3588 17.58                1
    ## 3589 17.58                1
    ## 3590 17.58                1
    ## 3591 17.58                1
    ## 3592 17.58                1
    ## 3593 17.58                1
    ## 3594 17.58                1
    ## 3595 17.58                1
    ## 3596 17.58                1
    ## 3597 17.58                1
    ## 3598 17.58                1
    ## 3599 17.58                1
    ## 3600 17.58                1
    ## 3601 17.58                1
    ## 3602 17.58                1
    ## 3603 17.58                1
    ## 3604 17.58                1
    ## 3605 17.58                1
    ## 3606 17.58                1
    ## 3607 17.58                1
    ## 3608 17.58                1
    ## 3609 17.58                1
    ## 3610 17.58                1
    ## 3611 17.58                1
    ## 3612 17.58                1
    ## 3613 17.58                1
    ## 3614 17.58                1
    ## 3615 17.58                1
    ## 3616 17.58                1
    ## 3617 17.58                1
    ## 3618 17.58                1
    ## 3619 17.58                1
    ## 3620 17.58                1
    ## 3621 17.58                1
    ## 3622 17.58                1
    ## 3623 17.58                1
    ## 3624 17.58                1
    ## 3625 17.58                1
    ## 3626 17.58                1
    ## 3627 17.58                1
    ## 3628 17.58                1
    ## 3629 17.58                1
    ## 3630 17.58                1
    ## 3631 17.58                1
    ## 3632 17.58                1
    ## 3633 17.58                1
    ## 3634 17.58                1
    ## 3635 17.58                1
    ## 3636 17.58                1
    ## 3637 17.58                1
    ## 3638 17.58                1
    ## 3639 17.58                1
    ## 3640 17.58                1
    ## 3641 17.58                1
    ## 3642 17.58                1
    ## 3643 17.58                1
    ## 3644 17.58                1
    ## 3645 17.58                1
    ## 3646 17.58                1
    ## 3647 17.58                1
    ## 3648 17.58                1
    ## 3649 17.58                1
    ## 3650 17.58                1
    ## 3651 17.58                1
    ## 3652 17.58                1
    ## 3653 17.58                1
    ## 3654 17.58                1
    ## 3655 17.58                1
    ## 3656 17.58                1
    ## 3657 17.58                1
    ## 3658 17.58                1
    ## 3659 17.58                1
    ## 3660 17.58                1
    ## 3661 17.58                1
    ## 3662 17.58                1
    ## 3663 17.58                1
    ## 3664 17.58                1
    ## 3665 17.58                1
    ## 3666 17.58                1
    ## 3667 17.58                1
    ## 3668 17.58                1
    ## 3669 17.58                1
    ## 3670 17.58                1
    ## 3671 17.58                1
    ## 3672 17.58                1
    ## 3673 17.58                1
    ## 3674 17.58                1
    ## 3675 17.58                1
    ## 3676 17.58                1
    ## 3677 17.58                1
    ## 3678 17.58                1
    ## 3679 17.58                1
    ## 3680 17.58                1
    ## 3681 17.58                1
    ## 3682 17.58                1
    ## 3683 17.58                1
    ## 3684 17.58                1
    ## 3685 17.58                1
    ## 3686 17.58                1
    ## 3687 17.58                1
    ## 3688 17.58                1
    ## 3689 17.58                1
    ## 3690 17.58                1
    ## 3691 17.58                1
    ## 3692 17.58                1
    ## 3693 17.58                1
    ## 3694 17.58                1
    ## 3695 17.58                1
    ## 3696 17.58                1
    ## 3697 17.58                1
    ## 3698 17.58                1
    ## 3699 17.58                1
    ## 3700 17.58                1
    ## 3701 17.58                1
    ## 3702 17.58                1
    ## 3703 17.58                1
    ## 3704 17.58                1
    ## 3705 17.58                1
    ## 3706 17.58                1
    ## 3707 17.58                1
    ## 3708 17.58                1
    ## 3709 17.58                1
    ## 3710 17.58                1
    ## 3711 17.58                1
    ## 3712 17.58                1
    ## 3713 17.58                1
    ## 3714 17.58                1
    ## 3715 17.58                1
    ## 3716 17.58                1
    ## 3717 17.58                1
    ## 3718 17.58                1
    ## 3719 17.58                1
    ## 3720 17.58                1
    ## 3721 17.58                1
    ## 3722 17.58                1
    ## 3723 17.58                1
    ## 3724 17.58                1
    ## 3725 17.58                1
    ## 3726 17.58                1
    ## 3727 17.58                1
    ## 3728 17.58                1
    ## 3729 17.58                1
    ## 3730 17.58                1
    ## 3731 17.58                1
    ## 3732 17.58                1
    ## 3733 17.58                1
    ## 3734 17.58                1
    ## 3735 17.58                1
    ## 3736 17.58                1
    ## 3737 17.58                1
    ## 3738 17.58                1
    ## 3739 17.58                1
    ## 3740 17.58                1
    ## 3741 17.58                1
    ## 3742 17.58                1
    ## 3743 17.58                1
    ## 3744 17.58                1
    ## 3745 17.58                1
    ## 3746 17.58                1
    ## 3747 17.58                1
    ## 3748 17.58                1
    ## 3749 17.58                1
    ## 3750 17.58                1
    ## 3751 17.58                1
    ## 3752 17.58                1
    ## 3753 17.58                1
    ## 3754 17.58                1
    ## 3755 17.58                1
    ## 3756 17.58                1
    ## 3757 17.58                1
    ## 3758 17.58                1
    ## 3759 17.58                1
    ## 3760 17.58                1
    ## 3761 17.58                1
    ## 3762 17.58                1
    ## 3763 17.58                1
    ## 3764 17.58                1
    ## 3765 17.58                1
    ## 3766 17.58                1
    ## 3767 17.58                1
    ## 3768 17.58                1
    ## 3769 17.58                1
    ## 3770 17.58                1
    ## 3771 17.58                1
    ## 3772 17.58                1
    ## 3773 17.58                1
    ## 3774 17.58                1
    ## 3775 17.58                1
    ## 3776 17.58                1
    ## 3777 17.58                1
    ## 3778 17.58                1
    ## 3779 17.58                1
    ## 3780 17.58                1
    ## 3781 17.58                1
    ## 3782 17.58                1
    ## 3783 17.58                1
    ## 3784 17.58                1
    ## 3785 17.58                1
    ## 3786 17.58                1
    ## 3787 17.58                1
    ## 3788 17.58                1
    ## 3789 17.58                1
    ## 3790 17.58                1
    ## 3791 17.58                1
    ## 3792 17.58                1
    ## 3793 17.58                1
    ## 3794 17.58                1
    ## 3795 17.58                1
    ## 3796 17.58                1
    ## 3797 17.58                1
    ## 3798 17.58                1
    ## 3799 17.58                1
    ## 3800 17.58                1
    ## 3801 17.58                1
    ## 3802 17.58                1
    ## 3803 17.58                1
    ## 3804 17.58                1
    ## 3805 17.58                1
    ## 3806 17.58                1
    ## 3807 17.58                1
    ## 3808 17.58                1
    ## 3809 17.58                1
    ## 3810 17.58                1
    ## 3811 17.58                1
    ## 3812 17.58                1
    ## 3813 17.58                1
    ## 3814 17.58                1
    ## 3815 17.58                1
    ## 3816 17.58                1
    ## 3817 17.58                1
    ## 3818 17.58                1
    ## 3819 17.58                1
    ## 3820 17.58                1
    ## 3821 17.58                1
    ## 3822 17.58                1
    ## 3823 17.58                1
    ## 3824 17.58                1
    ## 3825 17.58                1
    ## 3826 17.58                1
    ## 3827 17.58                1
    ## 3828 17.58                1
    ## 3829 17.58                1
    ## 3830 17.58                1
    ## 3831 17.58                1
    ## 3832 17.58                1
    ## 3833 17.58                1
    ## 3834 17.58                1
    ## 3835 17.58                1
    ## 3836 17.58                1
    ## 3837 17.58                1
    ## 3838 17.58                1
    ## 3839 17.58                1
    ## 3840 17.58                1
    ## 3841 17.58                1
    ## 3842 17.58                1
    ## 3843 17.58                1
    ## 3844 17.58                1
    ## 3845 17.58                1
    ## 3846 17.58                1
    ## 3847 17.58                1
    ## 3848 17.58                1
    ## 3849 17.58                1
    ## 3850 17.58                1
    ## 3851 17.58                1
    ## 3852 17.58                1
    ## 3853 17.58                1
    ## 3854 17.58                1
    ## 3855 17.58                1
    ## 3856 17.58                1
    ## 3857 17.58                1
    ## 3858 17.58                1
    ## 3859 17.58                1
    ## 3860 17.58                1
    ## 3861 17.58                1
    ## 3862 17.58                1
    ## 3863 17.58                1
    ## 3864 17.58                1
    ## 3865 17.58                1
    ## 3866 17.58                1
    ## 3867 17.58                1
    ## 3868 17.58                1
    ## 3869 17.58                1
    ## 3870 17.58                1
    ## 3871 17.58                1
    ## 3872 17.58                1
    ## 3873 17.58                1
    ## 3874 17.58                1
    ## 3875 17.58                1
    ## 3876 17.58                1
    ## 3877 17.58                1
    ## 3878 17.58                1
    ## 3879 17.58                1
    ## 3880 17.58                1
    ## 3881 17.58                1
    ## 3882 17.58                1
    ## 3883 17.58                1
    ## 3884 17.58                1
    ## 3885 17.58                1
    ## 3886 17.58                1
    ## 3887 17.58                1
    ## 3888 17.58                1
    ## 3889 17.58                1
    ## 3890 17.58                1
    ## 3891 17.58                1
    ## 3892 17.58                1
    ## 3893 17.58                1
    ## 3894 17.58                1
    ## 3895 17.58                1
    ## 3896 17.58                1
    ## 3897 17.58                1
    ## 3898 17.58                1
    ## 3899 17.58                1
    ## 3900 17.58                1
    ## 3901 17.58                1
    ## 3902 17.58                1
    ## 3903 17.58                1
    ## 3904 17.58                1
    ## 3905 17.58                1
    ## 3906 17.58                1
    ## 3907 17.58                1
    ## 3908 17.58                1
    ## 3909 17.58                1
    ## 3910 17.58                1
    ## 3911 17.58                1
    ## 3912 17.58                1
    ## 3913 17.58                1
    ## 3914 17.58                1
    ## 3915 17.58                1
    ## 3916 17.58                1
    ## 3917 17.58                1
    ## 3918 17.58                1

### Use `optim()` with its default Nelder-Mead method to find the estimates of $\beta_0$ and $\beta_1$ that maximize $l$ over the data $x_1, \ldots, x_n, y_1, \ldots, y_n =$ `age`, `reached.menarche` from `menarche.cases`. Check your `optim()` estimates by making a graph with these elements:

``` r
opt.par = optim(par = c(.5, .5),
                fn = Log.Lik,
                gr = NULL,
                x = menarche.cases$age,
                y = menarche.cases$reached.menarche, 
                method = 'Nelder-Mead',
                lower = -Inf,
                upper = Inf)

opt.par
```

    ## $par
    ## [1] -21.220857   1.631518
    ## 
    ## $value
    ## [1] 819.6524
    ## 
    ## $counts
    ## function gradient 
    ##      109       NA 
    ## 
    ## $convergence
    ## [1] 0
    ## 
    ## $message
    ## NULL

The 3918 points (x=age, y=reached.menarche) from `menarche.cases`. Since
there are only 25 ages, these points would overlap a lot. To fix the
overlap, I used `jitter()` to add a little random noise to each vector
of coordinates. For example, `jitter(c(1, 2, 3))` gives something like
`c(1.044804, 1.936708, 2.925454)`.

``` r
## The 3918 points (x=age, y=reached.menarche) from menarche.cases with jitter
## to create random noise for age
x1 = c(jitter(menarche.cases$age))
y1 = c(menarche.cases$reached.menarche)
id1 = rep('menarche.cases', nrow(menarche.cases))
```

The 25 points $(x_i, y_i)$ where $x_i$ is the $i$th age in the original
`menarche` data frame, and $y_i$ is the proportion of girls of that age
who have reached menarche.

``` r
## 25 points (xi, yi) where xi is the ith age in the original menarche data frame, 
## and yi is the proportion of girls of that age who have reached menarche
x2 = c(menarche$Age)
y2 = c()

for (i in 1:nrow(menarche))
{
  y2 = append(y2, 1/menarche[i,]$Total * menarche[i,]$Menarche)
}

id2 = rep('menarch', nrow(menarche))
```

![](Maximum_Likelihood_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->
